### PR TITLE
adding more info in 'get_ui_states' command.

### PR DESCRIPTION
**Pull request by boltex**
Adds more info to the get_ui_states data

### CODE REVIEW

**Review by edreamleo — APPROVED** [review]

**Comment by edreamleo** [comment]
@boltex I didn't realize that you had submitted a PR. See my PR #3900.

I'll accept your PR if you like.

**Comment by boltex** [comment]
@edreamleo Thanks! I've put this one in 'draft' for I'm still working on leoInteg to get the 'detached' body feature to work (same as what I added to LeoJS last week) 

Also, you can delete #3900 as I'll deal with this myself & orchestrate with LeoInteg  - Sorry I didnt make it clearer in my original issue #3898 that I was "on it" :smile:

**Comment by edreamleo** [comment]
On Sun, May 5, 2024 at 12:12 PM Felix ***@***.***> wrote:

> Also, you can delete #3900
> <https://github.com/leo-editor/leo-editor/pull/3900> as I'll deal with
> this myself & orchestrate with LeoInteg
>
Closed.

Edward

**Comment by boltex** [comment]
@edreamleo - Hurray! I've made progress in LeoInteg with detached body panes that now work well enough with this new leoserver version, so I'm confident in turning this draft into a real pull request that is ready to be merged.

I'll release a new LeoInteg version that supports 'detached' body panes as soon as the new Leo version containing this leoserver.py update is released ! 

( no rush, as I know how releases can be many details to attend to ! )
😄

**Review by edreamleo — APPROVED** [review]

**Comment by edreamleo** [comment]
@boltex I've merged this PR.

**Pull request merged**
