### PR TITLE
PR for #4137: Automatically create @jupytext children

### PR DESCRIPTION
**Pull request by edreamleo**
See #4137 and [this ENB](https://groups.google.com/g/leo-editor/c/h6guQO1pW2w/m/g3G-YMoFAQAJ).

Thomas's prototype script inspired this project.

**Summary**

This PR causes Leo to split `@jupytext` nodes into a *flat* list of child nodes.
This splitting happens only the *first* time Leo reads such a node.
You can disable this action by adding any child node (including an empty node) to the `@jupytext` node.

**Tasks**

- [x] Complete `at.readOneAtJupytextNode`. It calls  ` jtm.create_outline` *only* in the proper circumstances.
- [x] Create  `jtm.create_outline` and verify that Leo calls it only as expected.
- [x] Create a unit test.
- [x] Complete `jtm.create_outline`.
- [x] Check that all tests pass.
- [x] Support a new setting, `@int jupytext-max-headline-length = 60`, with the default as shown.
- [x] Test with a substantial `.ipynb` file to ensure that the importer handles typical conventions.
- [x] Recover from errors in `jupytext.read`.
    This happened after I mistakenly created a bad `.ipynb` file.
- [x] Verify that changed indentation levels persist after a reload.
    It took only a few seconds to organize the outline by apparent markdown level.
- [x] Trigger `after-reading-external-file` and `before-writing-external-file` events.
- [x] Support `refresh-from-disk`.
- [x] Update LeoPyRef.py.

<details><summary><b>Terminology and Methods</b></summary>
<br>

The context of the methods involved is all-important. Here are the details.

**Terminology**

- Let **root** denote the position of  the `@jupytext` node that Leo is reading.
- Let the **pseudo-python text** (pseudo-text for short) denote the string returned by
  `jupytext.read` (or `jtm.read` for the `.ipynb` file corresponding to the `@jupytext` node.

**jtm.read(c, p)**

This method:
- returns the pseudo-text for the `@jupytext` node at position p, the root.
- is a helper for `at.readOneAtJupytextNode`. No other method calls `jtm.read`.

**jtm.create_outline(p)**

This method will create the outline for p, the root. Constraints:
- p.b must already contain the proper pseudo-text.
- p must have no children.
- The created children must tile the original pseudo-text, without gaps or rearrangements.

**at.readOneAtJupytextNode(p)**

This method:

- uses a slight variation of Leo's `@clean` algorithm.
- *always* calls `jtm.read` to get the pseudo-text.
- calls `jtm.create_outline` to create the root node's outline,
  but *only* when `at.readOneAtJupytextNode` populates `root.b` for the first time.
  Otherwise, `at.readOneAtJupytextNode` updates root's *existing* tree using the `@clean` algorithm.

</details>

### CODE REVIEW

**Review by tbpassin — CHANGES_REQUESTED** [review]
leoJupytextManager
-----------------------
### Lines 38 - 39
```
    def dump_notebook(self, nb: Any) -> None:
        """Dump a notebook (class nbformat.notebooknode.NotebookNode)"""
```

I don't know what "dump" means.  Please add a line or two saying what will be produced.

test_importers.py
---------------------

### Line 1773
`def run_jupytext_test(self, s: str, expected_results: tuple, brief: bool = False) -> None:`

Add docstring showing what the expected_results tuple items represent.  E.g.,

`expected_results = (cell type: int, cell content:str)1

This test file is going to have to get more complicated before we're done!

**Comment by edreamleo** [comment]
@tbpassin Now is not the time for a code review. Please be patient.

**Comment by edreamleo** [comment]
@tbpassin @HaveF @vitalije This PR is ready for review.

This code is good enough for Leo 6.8.2. Any potential enhancements must wait until 6.8.3. I'll say more in Leo's forum.

**Comment by HaveF** [comment]
SCR-20241030-gudq

Looks like there is a bug. Markdown headings are inconsistent. Also, is it better to keep the `#` in the markdown heading?

[python1.ipynb.zip](https://github.com/user-attachments/files/17564032/python1.ipynb.zip)

**Review by tbpassin — DISMISSED** [review]
leoJupytext.py
----------------

### Line 62

```
            if line and not line.startswith('%%') and len(line) > 10:
                return line
```

1. What should the headline be if its length is less than 10? It should not be blank.

2. Recommend returning the first 6 words instead for better readability.  E.g.,

```if line and not line.startswith('%%'):
      headline = ' '.join(line.split()[:5])
      return headline
```

### [no lines] 

Add an @nocolor directive to the start of each markdown cell to prevent the colorizer from coloring the contents as comments.  Colorized comments are usually less readable than normal text.

**Review by HaveF — APPROVED** [review]
LGTM

**Comment by edreamleo** [comment]
@tbpassin The new `jtm.compute_headline` does a much better job of creating headlines.  This method:
- Honors the `@int jupytext-max-headline-length` setting.
- Uses `textwrap.shorten`.

**Comment by tbpassin** [comment]
I don't find leoJupytext.py in LeoPyRef.  It's in the leo/core file tree, of course.

**Comment by edreamleo** [comment]
@tbpassin Thanks. Updating `LeoPyRef.leo` is now on this PR's checklist.

**Pull request merged**
