### PR TITLE
Added support for a 'get UNL' command to the leo server.

### LINKED ISSUE #3789: Support a 'get-unl' command in Leo's server
This would be nice to display the current node's unl like in the original Leo's status bar of any client connected to a leoserver instance.

(This should have been added in the last server revision. Why didn't I think of that? Let's just say I discovered UNLs very late in the process :) hehe! )

### PR DESCRIPTION
**Pull request by boltex**
Fixes #3789

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex I didn't see this PR because there was no 6.7.8 milestone.

**Review by edreamleo — CHANGES_REQUESTED** [review]
Using `c.config.getString('unl-status-kind')` seems like a bad idea. 

The following is my version from PR #3793 (now closed in favor of *this* PR):

```python

 def get_unl(self, param: Param) -> Response:
        """
        Return the unl as it appears in the status line for given position.
        
        By default, this is the full legacy (headline-based) unl.
        """
        tag = 'get_unl'
        p = self._get_p(param)
        valid_kinds = (
            'full-gnx',  #    'unl:gnx:' + f"//{c.fileName()}#{self.gnx}"
            'full-legacy',  # 'unl:'     + f"//{c.fileName()}#{'-->'.join(<parents_headline_list>)}"
        )
        kind = getattr(param, "unl-kind", None) or 'full-legacy'
        if kind not in valid_kinds:
            raise ServerError(f"{tag}: invalid unl-kind: {kind!r}")
        if kind == 'full-gnx':
            unl = p.get_full_legacy_UNL()
        else:
            unl = p.get_full_gnx_UNL()
        return self._make_minimal_response({"unl": unl})
```
What do you think?

**Review by edreamleo — CHANGES_REQUESTED** [review]
Also, I recommend using either ` p.get_full_legacy_UNL()` or `p.get_full_gnx_UNL()`.

That explicitly returns (to LeoInteg) the full file name, not the directory name.

**Comment by edreamleo** [comment]
@boltex This PR clearly affects LeoInteg, but unless I am mistaken LeoJS is likely to want to use similar logic.

Within LeoJS, `c.config.whatever` is irrelevant. The local (LeoJS) settings seem like they would determine the format of the unls.  Do you agree?

**Review by edreamleo — APPROVED** [review]
Thanks for making these changes.

**Comment by boltex** [comment]
oops this was not my final commit on this, its still full of bugs!

**Pull request merged**
