### PR TITLE
PR for #2439: mod_scripting.py

### PR DESCRIPTION
**Pull request by edreamleo**
See #2439.

### CODE REVIEW

**Review by edreamleo — COMMENTED** [review]
The new has_at_others function is as close as I can come to an exact match to the code's stated purpose.

**Review by edreamleo — COMMENTED** [review]
@boltex Please test the new code for yourself before reviewing :-)

**Review by boltex — APPROVED** [review]
I tried before and after with 'fake @others' and it now works as expected with your fix. 
The code itself seems  good now :) Thanks!

**Comment by edreamleo** [comment]
@boltex Thanks for the review.

**Pull request merged**
