### PR TITLE
Tbp vr3 refactor and cleanup, reduce technical debt

### PR DESCRIPTION
**Pull request by tbpassin**
This is the first of a number of PRs that will be spread out over time for Issue https://github.com/leo-editor/leo-editor/issues/4026

This PR should be merged into devel now to avoid a much larger one in the future.

pytest output:
```
============================ warnings summary ============================
leo\plugins\leo_babel\tests\lib_test.py:118
  C:\Tom\git\leo-editor\leo\plugins\leo_babel\tests\lib_test.py:118: PytestCollectionWarning: cannot collect test class 'TestCmdr' because it has a __init__ constructor (from: leo/plugins/leo_babel/tests/lib_test.py)
    class TestCmdr:

leo/unittests/commands/test_editFileCommands.py::TestEditFileCommands::test_diff_two_revs
  C:\Tom\git\leo-editor\leo\core\leoCommands.py:2264: DeprecationWarning: Testing an element's truth value will raise an exception in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
    assert xroot

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============== 932 passed, 2 skipped, 2 warnings in 29.36s ===============
```

### CODE REVIEW

**Review by edreamleo — APPROVED** [review]

**Comment by edreamleo** [comment]
@tbpassin Rev 7de9b41 in "devel" beautifies VR3.

**Comment by tbpassin** [comment]
Thanks!

**Comment by edreamleo** [comment]
@tbpassin You're welcome.

I've closed PR #4017 because it made too many changes to VR3.

PR #4033 makes no changes to VR3 at present.  We can work on the required changes to VR3 later.

**Comment by tbpassin** [comment]
Good. I really want to stay coordinated on this. I won't continue on any refactoring/cleanup work on VR3 until we finally work out the layout stuff.

**Pull request merged**
