### PR TITLE
Setupext clean - to address #1055

### PR DESCRIPTION
**Pull request by maphew**
looks like there's some conflicts to fix before merging in this PR... waiting to see what they are

### CODE REVIEW

**Comment by maphew** [comment]
well that was ugly. `leoDist.leo` had merge conflict which I needed to fix using the GitHub web editor because Meld on my laptop wasn't showing me everything, Or something. 

I inspected leoDist.leo in Leo afterwards and it seems to be okay.

**Comment by maphew** [comment]
Edward, please review leoDist.leo and ensure it's intact.

**Comment by edreamleo** [comment]
leoDist.leo loads properly.  It's probably fine.  Matt, you're now a better judge of its contents than I am now.

**Comment by maphew** [comment]
Thanks

**Pull request merged**
