### PR TITLE
PR for #3446: paste-retaining-clone bug

### PR DESCRIPTION
**Pull request by edreamleo**
See #3446. Closed in favor of PR #3455.

**Summary**

A blunder in `fc.linkChildrenToParents` has been fixed. This blunder may have affected paste-node as well as paste-retaining-clones.

**Analysis**

Both `child1` positions refer to a clone after `paste-retaining-clones` because both positions refer to the same vnode. But `child1` isn't *shown* as a clone after `paste-retaining-clones` because `child1.parents` has only one entry. 

Leo's drawing code writes a clone mark for `p` if  `p.isCloned()` is `True`.
`p.isCloned()` returns `bool(len(p.v.parents) > 1)`.

**The fix**

`paste-retaining-clones` must set the `v.parents` array correctly.

- [x] Create initially-failing unit test: `TestOutlineCommands.test_paste_retaining_clones`.
   This strong test now passes. It tests multiple cycles of undo/redo.
- [x] Fix a blunder in `fc.linkChildrenToParents`.
  Change: ` if not child.v.parents:` to `if p.v not in child.v.parents:`.

<details><summary>Testing Changes</summary>
<br>

Changes to `leoTest2.py`:

- [x] Add `LeoUnitTest.dump_clone_info`.
  Despite the large diff, `git-diff-pr` shows that this is the only real change.

Changes to `testOutlineCommands.py`:

- [x] Remove `TestOutlineCommands.setUp`.
- [x] Two legacy tests now call `self.create_test_sort_outline()` themselves.

</details>

<details><summary>Test Output: Before Bug Fix</summary>
<br>

The "Before" Dump. Note `child1.parents`.

```console
dump_clone_info C:/Repos/leo-editor/leo/core/LeoPyRef.leo

clone? 0 id(v): 2501595111920 gnx: TestLeoId.20230721053740.2: root       parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595112272 gnx: TestLeoId.20230721053740.4: aa         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595112448 gnx: TestLeoId.20230721053740.5: bb         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 1 id(v): 2501595112800 gnx: TestLeoId.20230721053740.7: child1     parents: [<VNode TestLeoId.20230721053740.6 cc>, <VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595112624 gnx: TestLeoId.20230721053740.6: cc         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 1 id(v): 2501595112800 gnx: TestLeoId.20230721053740.7:  child1    parents: [<VNode TestLeoId.20230721053740.6 cc>, <VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595113152 gnx: TestLeoId.20230721053740.8:  child2    parents: [<VNode TestLeoId.20230721053740.6 cc>]
```

The "after" dump.  gnxs are correct but `v.parents` are not.

```console
dump_clone_info C:/Repos/leo-editor/leo/core/LeoPyRef.leo

clone? 0 id(v): 2501595111920 gnx: TestLeoId.20230721053740.2: root       parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595112272 gnx: TestLeoId.20230721053740.4: aa         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595112448 gnx: TestLeoId.20230721053740.5: bb         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595112800 gnx: TestLeoId.20230721053740.7: child1     parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595112624 gnx: TestLeoId.20230721053740.6: cc         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595112800 gnx: TestLeoId.20230721053740.7:  child1    parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2501595113152 gnx: TestLeoId.20230721053740.8:  child2    parents: [<VNode TestLeoId.20230721053740.6 cc>]
```

</details>

<details><summary>Test Output: After Bug Fix</summary>
<br>

"Before" dump:

```console
dump_clone_info C:/Repos/leo-editor/leo/core/LeoPyRef.leo

clone? 0 id(v): 2600108433728 gnx: TestLeoId.20230721060702.2: root       parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2600108434080 gnx: TestLeoId.20230721060702.4: aa         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2600108434256 gnx: TestLeoId.20230721060702.5: bb         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 1 id(v): 2600108434608 gnx: TestLeoId.20230721060702.7: child1     parents: [<VNode TestLeoId.20230721060702.6 cc>, <VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2600108434432 gnx: TestLeoId.20230721060702.6: cc         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 1 id(v): 2600108434608 gnx: TestLeoId.20230721060702.7:  child1    parents: [<VNode TestLeoId.20230721060702.6 cc>, <VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2600108434960 gnx: TestLeoId.20230721060702.8:  child2    parents: [<VNode TestLeoId.20230721060702.6 cc>]
```

"After" Dump. Now all is well.

```console
dump_clone_info C:/Repos/leo-editor/leo/core/LeoPyRef.leo

clone? 0 id(v): 2600108433728 gnx: TestLeoId.20230721060702.2: root       parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2600108434080 gnx: TestLeoId.20230721060702.4: aa         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 0 id(v): 2600108434256 gnx: TestLeoId.20230721060702.5: bb         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 1 id(v): 2600108434608 gnx: TestLeoId.20230721060702.7: child1     parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>, <VNode TestLeoId.20230721060702.6 cc>]
clone? 0 id(v): 2600108434432 gnx: TestLeoId.20230721060702.6: cc         parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>]
clone? 1 id(v): 2600108434608 gnx: TestLeoId.20230721060702.7:  child1    parents: [<VNode hidden-root-vnode-gnx <hidden root vnode>>, <VNode TestLeoId.20230721060702.6 cc>]
clone? 0 id(v): 2600108434960 gnx: TestLeoId.20230721060702.8:  child2    parents: [<VNode TestLeoId.20230721060702.6 cc>]
```

</details>

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex It appears that a one-line fix will suffice.

**Comment by boltex** [comment]
I tried this fix, indeed the major bug described at the top of #3446 seems fixed...

Only issue that remains is the small and subtle one about the fact that **pasting retaining clones** should "enforce" the pasted content.

Example: in any software, (text image sound or whatever editing software) the clipboard can be used as a temporary 'store' for preserving something before a test in editing the content, and wanting to bring it back afterwards. 

Perhaps at the same place, perhaps someplace else. For instance, I cut or copy something that I care about, try a modification, don't like it, ...I may 'paste' it back in place somewhere instead of doing 'undos'. This is totally legit and used all the time in many daily instances working on many things on a computer.

So pasting retaining clones should enforce the pasted content's body text, headline string, and UA's when the gnx matches and the same VNodes are used thus restoring the 'clone' status of nodes being pasted with GNX matching those in the commander. (instead of just reusing the found VNode as-is)

Maybe this can be optional and used with a flagin order to be used for the undo/redo operations of arbitrary treeChanges

**Comment by boltex** [comment]
'paste-as-template' also has this same small remaining issue, that it does not 'enforce' the content of pasted 'clone' nodes when the body/headline/UA's are different.

**Comment by edreamleo** [comment]
@boltex Thanks for your comment. I'll attempt a fix for the "pasted-text wins" problem.

**Comment by edreamleo** [comment]
Closed in favor of PR #3455.

**Comment by edreamleo** [comment]
@boltex Ensure "pasted-nodes win" is on the to-do list for the unified PR: #3455.

**Pull request closed without merging**
