### PR TITLE
PR for #4037: Add reload-outline command

### PR DESCRIPTION
**Pull request by edreamleo**
See #4037.

- [x] Add the `reload-outline` command to `leo/plugins/qt_frame.py`.
- [x] Add a `reload-outline` menu entry to `leoSettings.py`.
- [x] Make disambiguating headlines more accurate in several files.

### CODE REVIEW

**Comment by tbpassin** [comment]
Don't we just about have this already with `revertCommander()`?

**Comment by edreamleo** [comment]
On Thu, Aug 8, 2024 at 11:42 AM Thomas Passin ***@***.***>
wrote:

> Don't we just about have this already with revertCommander()?
>
I'll look into it. But we don't necessarily want to revert any changes.

Edward

**Review by tbpassin — CHANGES_REQUESTED** [review]
1. Code around line 208ff uses wrong calls.  Use `insertTab()` instead.  Don't remove dw before changing index - inserting into the right index will be enough.  Also, from the Qt docs:

_Note: If you call insertTab() after [show](https://doc.qt.io/qt-6/qwidget.html#show)(), the layout system will try to adjust to the changes in its widgets hierarchy and may cause flicker. To prevent this, you can set the [QWidget::updatesEnabled](https://doc.qt.io/qt-6/qwidget.html#updatesEnabled-prop) property to false prior to changes; remember to set the property to true when the changes are done, making the widget receive paint events again._

Something like this (untested):
```
        if is_qt:
            dw = c.frame.top
            tabbed_widget = dw.parent()
            new_index = tabbed_widget.indexOf(dw)
            g.trace(new_index, old_index)
            if new_index != old_index:
                tabbed_widget.setUpdatesEnabled(False)
                tabbed_widget.insertTab(old_index, dw, <tabname>)
                tabbed_widget.setUpdatesEnabled(True)
                dw.show()
```
2. Need an alternative for when `is_qt ` is `False`.

**Comment by edreamleo** [comment]
@tbpassin Thanks for the hints. I'll give them a try later today.

**Comment by edreamleo** [comment]
@tbpassin `LM.revertCommander` is not what we want for this issue.

**Comment by edreamleo** [comment]
@tbpassin The code you suggest does not work:

- `QStackedWidget.insertTab does not exist.
- `tabbed_widget.insertWidget(old_index, dw)` does not seem to work.

**Comment by edreamleo** [comment]
@tbpassin I have removed the code that saves & restores the widget index. The suggestions you made do not work.

I'm happy enough with the latest code.

**Comment by edreamleo** [comment]
@tbpassin Heh. I forgot that there is another possible way forward. A hack could tell the `LeoQtGui` class where to put the outline.

This strategy might avoid problems (including possible Qt bugs) involved with attempts to *move* tabs.

I'll try this way next.

**Comment by tbpassin** [comment]
> @tbpassin The code you suggest does not work:
> 
> * `QStackedWidget.insertTab does not exist.
> * `tabbed_widget.insertWidget(old_index, dw)` does not seem to work.

It works if you use a QTabWidget.  My example was for a QTabWidget. The actual widget is supposed to be a QTabWidget, right? See attached:

[tabwidget_insert_demo.zip](https://github.com/user-attachments/files/16553764/tabwidget_insert_demo.zip)

**Comment by edreamleo** [comment]
@tbpassin It seems that I did not understand Leo's widget structure :-)

The docstring for the `DynamicWindow` class contains this:
```
c.frame.top is a DynamicWindow.
c.frame.top.leo_master is a LeoTabbedTopLevel, a subclass of QTabWidget.
c.frame.top.parent() is a QStackedWidget()
```
This is *good* news, but I don't yet know how to take advantage of it.

I'll be writing an Engineering Notebook post about all this.

**Comment by edreamleo** [comment]
@tbpassin This PR is ready for review. In most cases `reload-outline` is nearly instantaneous.

**Review by tbpassin — CHANGES_REQUESTED** [review]
**qt_frame.py**
----------------
** - Line 2168** - `LeoQtFrame.destroyAllObjects`
If this is not used then let's remove it.

**- Line 2482**:
```
        if not c.fileName():
            c.save()
```
This should read
```
        if c.fileName():
            c.save()
```
The following line should be replaced with `else:`:

`if not c.fileName()` --> `else:`

**- Line 2508 ff** - `stacked_layout = stacked_widget.indexOf(QStackedLayout)` should replace the loop.

**- Lines 2541 ff ** - 
```
 # Fix all tab names.
        for i, name in enumerate(tab_names):
            tab_widget.setTabText(i, name)
```

Doesn't the insertion into the target index automatically accomplish this?

**freewin.py**
---------------
**Line 759** - Changes to freewin do not belong in this PR.  Please revert.

**Comment by edreamleo** [comment]
@tbpassin Some comments:

- I've moved `destroyAllObjects` to the attic, and cleared old items from the attic.
- The strange-looking tests of `c.fileName()` are correct.
- Replacing the tab names by hand was the only approach that worked for me.
- I often add disambiguating headlines where needed.

**Comment by edreamleo** [comment]
@tbpassin Oops.  PR #4045 removes `destroyAllObjects`.

**Pull request merged**
