### PR TITLE
PR for #2145

### PR DESCRIPTION
**Pull request by edreamleo**
See #2145 for the to-do list.

### CODE REVIEW

**Review by boltex — COMMENTED** [review]
mispelled wsSkipDirty as wsSkipDirt

**Comment by edreamleo** [comment]
@boltex Good catch on the misspelling. It was consequential.

**Comment by edreamleo** [comment]
@boltex I have completed this issue.  Please do the following:
- Test the traces.
- Review the description with --help.

**Comment by edreamleo** [comment]
@boltex Please make any changes you like in felix-server4. I plan no further work on #2145.

**Pull request merged**
