### PR TITLE
PR for #3447: show-file-line

### PR DESCRIPTION
**Pull request by edreamleo**
See #3447.

- This PR fixes several problems with the `show-file-line` command and adds an extensive new unit test.
- However, this command contains a bug that can not be fixed with any reasonable amount of work.
- The command is seldom used, but I see no urgent reason to retire it.
  Otoh, I see no reason for `show-file-line` to exist in leoJS.

<details><summary>Details</summary>
<br>

- [x] Add `g. is_invisible_sentinel`. This new resource handles all the details correctly.
- [x] Add `at.atCleanToString`, an independent check on `g. is_invisible_sentinel`.
- [x] Add `goto.prev_hidden_lines`.  It calls `g. is_invisible_sentinel`.
- [x] Add `goto.get_3_delims`. It simplifies calling `g.is_sentinels`.
- [x] Revise `goto.find_node_start`, fixing several bugs.
- [x] Add `TestGotoCommands.test_show_file_line`.
  - [x] Test equivalence of `at.atCleanToString` and `g. is_invisible_sentinel`.
  - [x] Test `goto.find_node_start`, the helper for `show-file-line`.
  - [x] Test `goto.find_file_line`, the helper for `goto-global-line`.

</details>

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex I plan no further changes.

`goto-global-line` and `show-file-line` also pass hand tests.

**Comment by edreamleo** [comment]
@boltex Drat. Hand tests show there are still problems with `@clean`.

**Comment by edreamleo** [comment]
@boltex I've changed my mind. This PR is good enough as it is:

- Hand tests show that Leo resolves error links properly in both `@file` and `@clean` files.
- PR [#3480](https://github.com/leo-editor/leo-editor/pull/3480) Is much more important than this PR.

**Comment by edreamleo** [comment]
@boltex I am going to merge this PR as is. If necessary, we can fix any urgent problems in a follow-on PR.

**Comment by boltex** [comment]
@edreamleo oops: I pulled devel and can see the new gotocommands related code, I think leopyref.leo does not contain the new test-gotoCommands unit test node.

**Review by boltex — COMMENTED** [review]
I've also implemented all of this in leojs's branch devel. All tests pass and behavior is same as Leo now. :)

**Comment by edreamleo** [comment]
@boltex Thanks for adding all this to leojs.

Rev cfb2bcb updates LeoPyRef.leo. `@button check-leoPy.leo now checks the `leo/unittests` directory for missing files.

**Pull request merged**
