### PR TITLE
PR for #3310: problems with @language md

### PR DESCRIPTION
**Pull request by edreamleo**
See #3310.

- [x] Fix two regexs in `md.py`. These errors predate Leo 6.7.2.
- [x] Require `kind` arg to be a kwarg.
- [x] Update `self.modes[rulesetName]` in `init_mode_from_module`. This fixes the reported problem.
- [x] Improve the traces produced by the `report` function in the `setTag` method:
  - Remove the `match_name` ivar. It was updated too late to appear in the traces.
  - The `match_name` var is the caller three-levels up.

### CODE REVIEW

**Review by tbpassin — COMMENTED** [review]
1. leoColorizer, line 2086.  I'm a little concerned that some existing code may break if the "kind" arg is made a KW arg.  I like the idea in principle.

2. Same comment for line 2214.

3. General style comment:  I thought we were moving to consistently putting spaces around "=" signs in function args.  E.g., `kind = "markup"` instead of `kind="markup"`.

4. This PR only patches a couple of mode files.  What about all the dozens of other ones?  Don't they need `kind = ...` too?

These are all pretty superficial comments, and of course the proof of the pudding will be in the eating.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comments.

**Points 1, 2 & 4**: Requiring `kind` to be a kwarg reverts to the status quo ante. All existing mode files specify `kind` as a kwarg. Furthermore, there is a unit test that checks the syntax of many of Leo's files, including `leo/modes/*.py`. Those tests would fail if any mode file had a problem.

**Point 3**: Beautifying all files in `leo/modes` changed only one comment in `perl.py`. These mode files almost never change, so there is no need for `leo/scripts/beautify-leo.cmd` to contain:

    call py -m leo.core.leoAst --orange --recursive leo\modes

As you say, the proof will be in the eating. I'll merge this PR and we'll all continue testing.

**Comment by tbpassin** [comment]
> Requiring `kind` to be a kwarg reverts to the status quo ante. All existing mode files specify `kind` as a kwarg

Sorry, I didn't make myself clear.  I agree with your proposed changes in the "kind" arg and was only concerned in case some other code that didn't get looked at uses it the old way.

**Comment by edreamleo** [comment]
@tbpassin Afaik, only leoColorizer.py uses the mode files.

**Pull request merged**
