### PR TITLE
Boltex/issue3760

### LINKED ISSUE #3760: Modify leoserver.py to support handling UNL links from connected clients.
As the title says, the leoserver should handle UNL strings from a connected client if at least a commander is opened.

Also modify app.selectLeoWindow to check for g.leoserver after checking for top frame. (make it select the appropriate commander)

The app.findOpenFile method should perhaps also use app.selectLeoWindow.

### PR DESCRIPTION
**Pull request by boltex**
Updated leoBridge to remove hard-coded cheat for LeoInteg. Server now hooks onto 'open2' event to finalize newly created commander that would normally be added to the window tabs.
Added missing 'open' hook events to openExternalFile. (to match the two other source of opened documents in leoApp.py)
Added UNL support to leoserver.py.
Fixes #3760

### CODE REVIEW

**Review by boltex — COMMENTED** [review]
Big improvements on leoserver for UNL click support and other general improvements to the server! :)

**Comment by boltex** [comment]
I've made it a draft for now as I'd like to add one more small feature to the server still :)

**Review by edreamleo — CHANGES_REQUESTED** [review]
Looks good.

PR #3762 changes various documentation files, especially `LeoDocs.leo`. I've converted `leoInteg` to `LeoInteg` there. Ditto for `leoJS` to `LeoJS`.

So please revert `LeoDocs.leo` and `acknowledgements.html.txt.txt` to devel. That will make it easier for me to merge my branch.

**Comment by boltex** [comment]
@edreamleo Even better: I'll wait until you merge #3762 into devel, then I'll pull devel into #3760, making sure any conflicts are resolved and dealt into #3760 by myself, (if any). 

Then you will be able to merge it into devel without any conflicts for sure.

The trouble of providing a branch to be merged smoothly without any conflicts to resolve should rest on the person making the new feature branch. 

You should not have to worry about annoying merge conflicts on top of the rest! 😆

**Review by edreamleo — APPROVED** [review]

**Comment by edreamleo** [comment]
@boltex I've merged #3762 into devel, so have at it :-)

**Comment by boltex** [comment]
**About unit tests** 

The new leoserver system now uses the open2 'doHook' event. 

When running tests, if I run only the 'TestLeoServer' tests, they pass. But if I launch all tests, I think something in the unit tests preceding the server tests turns off the 'doHook' events, and they fail. 

I don't know enough about the python unit tests system to resolve this :/

(_as you can see in the screenshot below, in vscode I can press 'play' on on any unit tests subsection, and pressing play to run only the server tests makes them run without issue, but running the whole suite of Leo's unit tests make the server tests fails because the hook events do not trigger somehow)_
image

Below is that same section after trying to run all tests:
image

**Comment by boltex** [comment]
@tbpassin @edreamleo These modifications on leoserver.py enables many new features in leoInteg, among which, the possibility to right-click on an @button originating from another file (myLeoSettings.leo containing @buttons outlines) and choose 'goto-script' to find the @buttons script origin node! 😄 Thanks to @tbpassin for letting me know about this missing feature when he tested LeoJS! (which also now supports this feature)

I'll release the new LeoInteg version as soon as Leo 6.7.7. is launched! 🚀

**Comment by edreamleo** [comment]
I just tested this branch. Here are the results:
```console
ft.cmd
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................EException in test_most_public_server_methods: 'find_quick_changed' 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'find_quick_history' 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'find_quick_marked' 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'find_quick_timeline' 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'get_goto_panel' get_goto_panel: exception doing nav search: 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'get_search_settings' 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'goto_nav_entry' 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'interactive_search' 'NoneType' object has no attribute 'set_find_text'
Exception in test_most_public_server_methods: 'nav_clear' 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'nav_headline_search' nav_headline_search: exception doing nav headline search: 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'nav_search' 'Commands' object has no attribute 'patched_quicksearch_controller'
Exception in test_most_public_server_methods: 'replace' replace: Running change operation gave exception: 'NoneType' object has no attribute 'get_settings'
Exception in test_most_public_server_methods: 'replace_all' replace_all: Running change operation gave exception: 'NoneType' object has no attribute 'get_settings'
Exception in test_most_public_server_methods: 'replace_then_find' replace_then_find: Running change operation gave exception: 'NoneType' object has no attribute 'get_settings'
.E..................................................................................................................................
======================================================================
ERROR: test_find_commands (leo.unittests.core.test_leoserver.TestLeoServer.test_find_commands)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 1937, in find_all
    settings = fc.ftm.get_settings()
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Repos\leo-editor\leo\unittests\core\test_leoserver.py", line 194, in test_find_commands
    answer = self._request(method, {"log": log, "find_text": "def"})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\unittests\core\test_leoserver.py", line 64, in _request
    response = server._do_message(d)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 4769, in _do_message
    result = func(action, param)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 4785, in _do_server_command
    return func(param)
           ^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 1940, in find_all
    raise ServerError(f"{tag}: exception running 'find all': {e}")
leo.core.leoserver.ServerError: find_all: exception running 'find all': 'NoneType' object has no attribute 'get_settings'

======================================================================
ERROR: test_open_and_close (leo.unittests.core.test_leoserver.TestLeoServer.test_open_and_close)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Repos\leo-editor\leo\unittests\core\test_leoserver.py", line 181, in test_open_and_close
    self._request(action, package)
  File "C:\Repos\leo-editor\leo\unittests\core\test_leoserver.py", line 64, in _request
    response = server._do_message(d)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 4769, in _do_message
    result = func(action, param)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 4785, in _do_server_command
    return func(param)
           ^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 1336, in close_file
    c = self._check_c(param)
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 4591, in _check_c
    raise ServerError(f"{tag}: no open commander")
leo.core.leoserver.ServerError: _check_c: no open commander

----------------------------------------------------------------------
Ran 895 tests in 6.709s

FAILED (errors=2)
ruff leo\core,  leo\commands, leo\plugins\qt...
leo\core\leoserver.py:1606:29: F841 [*] Local variable `e` is assigned to but never used
Found 1 error.
[*] 1 fixable with the `--fix` option.

mypy-leo
Success: no issues found in 260 source files
Done!

C:\Repos\leo-editor>
```

**Comment by edreamleo** [comment]
@boltex I'll release Leo 6.7.7 as soon as we merge this PR. I'll move all other issues to 6.7.8.

**Comment by boltex** [comment]
@edreamleo I found a way! 😄

**Review by edreamleo — CHANGES_REQUESTED** [review]
Elegant fix at line 1275. However, the test should use isinstance:

`if g.unitTesting and isinstance(g.app.pluginsController, NullObject):`

**Comment by edreamleo** [comment]
@boltex Or probably `isinstance(g.app.pluginsController, g.NullObject)`

**Comment by edreamleo** [comment]
@boltex dc919a5 fixes some quirps.

The most serious: pylint pointed out that at lines 5124 and 5128 the code should *raise* the indicated exceptions. However, running the unit tests raises the exception at line 5128 (marked with '###'). Perhaps `if not g.unitTesting:` should replace `if 0:` ?

What do you think?

**Comment by edreamleo** [comment]
@boltex ad5d0f3 suppresses the exception during unit tests. I'll approve the present code. Feel free to tweak.

**Comment by boltex** [comment]
I've looked at what you've tuned up and it looks good. I've also re-tested the new features just to make sure. It all still works, so this looks very good to me 😄

**Comment by boltex** [comment]
@edreamleo Many thanks to you for those fixes!

**Review by edreamleo — APPROVED** [review]

**Pull request merged**
