### PR TITLE
PR for #3181: new unls

### PR DESCRIPTION
**Pull request by edreamleo**
This PR fixes two bugs: #3181 (a small bug) and #3404 (a serious bug).
This PR also completes #1868 (gnx-based UNLs).

**Summary of changes**

This is the biggest little bug fix in Leo's history.

- Fix the original bug [#3181](https://github.com/leo-editor/leo-editor/issues/3181) by adding a special case in `goto.find_file_line`.
- Support *optional* gnx-based unls. See the new settings below.
  `g.findGnx`, `g.parsePathData`, and `g.openUNLFile` are powerful new resources for scripts and plugins.
- Add the `--save-session` command-line argument.
- The `convert-unls` command converts legacy (path-based) unls to gnx-based unls.
- Document clickable links in Leo's Users Guide.
- Retire the  dangerous `settings_finder` plugin.
- Retire the  `backlink` and `quickMove` plugins.
  Cross-file gnxs render these plugins obsolete.

**New Settings**

leoSettings.leo contains the following new settings, with defaults as shown.

- `@string unl-status-kind = legacy`.
- `@bool full-unl-paths = True`.
- `@data unl-path-prefixes` (with only comments in the body).

With these settings, Leo should treat unls *exactly* as before.

<details><summary>Code-level details</summary>
<br>

**Most important methods**

- `g.openUNLFile` opens the commander for a unl using the data in `@data unl-path-prefixes`.
- `g.parsePathData` creates a dictionary from the `@data @data unl-path-prefixes` setting.
- `g.findUnl` (aka `g.findUNL`) resolves legacy (path-based) unls (to a position).
- `g.findGnx` resolves new (gnx-based) unls.
- `g.handleUNL` opens other outlines using the file part of a legacy unl.
- `p.get_UNL` returns the (clickable) unl for p. This is not the same as p.gnx!

*Note*: Leo's `@auto` code creates and uses links similar to Leo's legacy unls.
However, the `PersistenceDataController` class uses neither `p.get_UNL` nor `g.findUnl`.

**Code-level changes and cleanups**

- [x] Update `SM.load_session` so it handles new unls correctly.
- [x] Call `urllib.parse.quote` in `LeoQtLog.put`. Call `urllib.parse.unquote` in `LeoQtLog.linkClicked`.
    Remove url/unl hacks in `LeoQtLog.put`.
- [x] Do *no* gui-related operations in `g.findUNL`.
- [x] Remove `link_root` kwargs and related ivars.
- [x] Remove `link_pattern` kwargs and related ivars.
- [x] Set `c.fileName` in `LeoUnitTest.setUp`.
- [x] `LeoUnitTest.setUpClass`: set a valid file name in the `Commands` class.

**Other changes**

- [x] Fix [#3404](https://github.com/leo-editor/leo-editor/issues/3404) in *this* PR. See `LM.openWorkBook`.
- [x] `p.get_UNL` returns unls per `@string unl-status-kind` and  `@bool full-unl-paths`.
- [x] Add `p.get_legacy_UNL` and `p.get_short_legacy_UNL` for use by plugins.
- [x] Add `g.findAnyUnl` and `g.isAnyUnl`.
- [x] Change `g.findGNX` to `g.findAnyUnl` in all plugins.
- [x] Add `<< About clickable links >>` section in `leoGlobals.py`.
- [x] Add `@button copy-test` to `test.leo`.
- [x] Add `gnx-show` and `show-gnx` as aliases for `copy-gnx`.

</details>

### CODE REVIEW

**Review by tbpassin — CHANGES_REQUESTED** [review]
1. 
```
def findUnl(unlList1: list[str], c: Cmdr) -> Optional[Position]:
    """
    g.findUnl: support for legacy UNLs.
    This method must remain for compatibily with plugins.
```
Docstring should specify format for _unlList1_.  Without documentation, it seems like it would be a list of UNLs, but actually (I think) it's a list of *steps* within a single UNL.
Also, correct spelling of "compatibily".

2.  Just a question, not a complaint.  In line 1255, why is `c.setBodyString(p, ...)` better than `p.b = ...`?
3. A general remark - this PR does too many things.  One example is changing names of commands, such as _tsToPy_ to _typescript_to_py_.  Yes, this is a good change but it should have been in a separate PR.  Another example is removing _link_pattern_ and _link_root_ from some method signatures.  This should have been done in a separate PR. A third example is in leoFrame.py, line 1253ff, which reformats the method signature.  This is a worthy thing to do, but it should have been in a different PR.  Changes in leoUndo also belong in a different PR.
4. gotoCommands, line 287 - `# Look up the tree @file node.` Change to read `# Look up the tree for the first @file node.`
5. In LeoSettings.leo, the setting `@string unl-status-kind = gnx` appears in two places.
6. In leoBackground.py, line 177 -`Put a string to the originating log. *Not* the same as g.es_print!` - this is an improvement over the previous version but please say **what is different**.
7. leoGlobals.py - Inconsistent spellings `<< define regex's >>`, vs `<< define global error regexes >>`
8. Line 7424, leoGlobals.py - `def handleUnl(unl_s: str, c: Cmdr)`:
   Docstring should say if this handles a gnx-style unl, path-based, or both.
9. Line 7526. `def isValidUnl(unl_s: str)` - same comment.
10. Line 7726, leoGlobals.py -
```
def openUNLFile(c: Cmdr, s: str) -> Cmdr:
    """
    Open the commander s.
    Return c if the file can not be found.
    """
```
This signature + docstring is hard to understand.  What is "s" supposed to be?  The docstring says to "Open the commander s.", But s is a string, not a commander, and we've already got a commander as the first arg.  Please clarify the signature, docstring, or both.
11. Line 7754, leoGlobals.py - 
```
def parsePathData(c: Cmdr) -> dict[str, str]:
    """Return a dict giving path prefixes for various files."""
```
What does this mean, "various" files?  Please clarify.

I have not reviewed changes to LeoDocs or to any plugins.

[Later] I forgot to check what happens when there is a short filename setting in effect but the user writes a complete path.

**Comment by tbpassin** [comment]
By "Never save the notebook on startup. Create an empty notebook" I hope you mean when Leo starts up for the first time and had to create a user.

**Comment by edreamleo** [comment]
@tbpassin Check-in notes are just short summaries.

I have rewritten and renamed `LM.openWorkBook()`. Please study it carefully. There are several notable changes:

- Don't bother copying the cheat sheet.
  Just create an outline whose only node is `Workbook`.
- Do *not* save the file and don't mark it dirty.
  Nothing will be lost if the user just closes the newly-created notebook.
  When Leo next opens, Leo will just call `LM.openWorkBook()` again.
- Do *not* call `c.redraw` and do not change `c.p`.
  Doing so destroyed the cached value of `c.p`!

**Comment by tbpassin** [comment]
Test-leo:
```
C:\Tom\git\leo-editor\leo\scripts>test-leo.cmd
'reindent-leo.cmd' is not recognized as an internal or external command,
operable program or batch file.
test-leo
[snip]
Ran 853 tests in 11.627s

OK (skipped=1)
```

Apparently _reindent-leo.cmd_ is still MIA.

`Leo 6.7.4-devel, ekr-3181-mypy-links branch, build 34e0b9d116`

**Comment by edreamleo** [comment]
@tbpassin I've just put Update LeoPyRef.leo on the checklist.

**Pull request merged**
