### PR TITLE
Added type annotations to freewin.py.

### PR DESCRIPTION
**Pull request by tbpassin**
pylint: 10/10
mypy: no issues

### CODE REVIEW

**Review by edreamleo — APPROVED** [review]

**Comment by edreamleo** [comment]
@tbpassin Thanks for this work!

**Comment by tbpassin** [comment]
My very first try at learning how to to it!

**Comment by edreamleo** [comment]
@tbpassin All went well except that the `@file node` had your local path in it. I have fixed this in devel.

**Comment by tbpassin** [comment]
Good catch!  I imported this file into another output to to the development to avoid those delays on saving with LeoPyRef.  Since it was the same file, I assumed it would be update in LeoPyRef with no problems.  Wrong again!

**Pull request merged**
