### PR TITLE
Make runAskYesNoDialog() work again, using direct query for which button was clicked.

### PR DESCRIPTION
**Pull request by tbpassin**
Fixes Issue https://github.com/leo-editor/leo-editor/issues/4012

Note that other similar dialogs may be broken the same way.  This PR only fixes this specific dialog.

### CODE REVIEW

**Review by gatesphere — APPROVED** [review]
I'm not sure how the previous code ever worked -- exec returns a QDialogCode (0 or 1), and has nothing to do with the order of the button creations.  If this behavior changed, it was prior to Qt5.15, the oldest version I can find docs for.

**Comment by tbpassin** [comment]
The return values were small integers - 2,3,4,5, not in that order, and I couldn't find anything on line about how to know what they would be.  Even ChatGPT let me down.  Anyway, the way in the PR is better because you can directly learn which button was clicked.  One Leo's other similar dialogs already uses a similar technique.

**Comment by edreamleo** [comment]
@tbpassin Thanks for this work.

I didn't realize you had created the PR. I wasn't informed somehow.

My PR #4020 uses `dialog.clickedButton()` as does this PR, but I like my PR a bit better.

What do you think?

**Comment by tbpassin** [comment]
I marked it as a critical bug, with the next available milestone.  I don't know what more I could have done.

**Comment by edreamleo** [comment]
@tbpassin Why are you still pushing to this branch? Let's let PR #4020 do the work.

**Comment by tbpassin** [comment]
I didn't mean to push it.  I update it to dev before deleting it and apparently Github presented that as pushing it.  Sorry.  Should be closed.

**Comment by edreamleo** [comment]
@tbpassin No problem.

**Pull request closed without merging**
