### PR TITLE
PR for #3190: crash in show-settings

### PR DESCRIPTION
**Pull request by edreamleo**
See #3190.

### CODE REVIEW

**Review by tbpassin — CHANGES_REQUESTED** [review]
I don't think this quite gets at my particular issue.  Instead of quitting if a key does not have a settings value, I would like that key to be skipped but the loop should continue.  In my case, somehow several outlines seem to have (non-reproducibly) loaded blank settings.  They do not need to fail an assertion, since they will not cause any harm.  Thus a continue statement is appropriate.  The assertion should still protect against incorrect types as it currently does.

**Comment by edreamleo** [comment]
@tbpassin Please change this PR or issue a new PR as you like.

**Comment by tbpassin** [comment]
> @tbpassin Please change this PR or issue a new PR as you like.

OK. How can I amend your PR?

**Comment by edreamleo** [comment]
I think you can check out my branch and then push your changes.  If not, just create your own branch, delete the offending assert and go from there.

**Comment by edreamleo** [comment]
@tbpassin I have resolved the original issue by replacing the `assert` with a comment.

In general, such `assert`s can do more harm than good.

**Pull request merged**
