### PR TITLE
VR3 - Simplify Code For Split Layouts; Change Default Layout

### PR DESCRIPTION
**Pull request by tbpassin**
- [x] Remove unneeded added splitter and simplify code. 
- [x] Make default layout more useful.

Previously the default layout bunched up VR3 into a small part of the secondary splitter, where it is hard to read.  Now the default is to open VR3 next to the body pane. Otherwise, when the main layout is vertical, VR3 opens in the log frame, again for better readability.

- [x] Add docstring to vr3.plot_2d() . This is displayed  by the "vr3-help-plot-2d" command.  It was a bug for it to be missing. 
- [x] Update version and What's New. 
- [x] Simplify and speed up `set_user_style()`  in the `vr3-plot-2d` minibuffer command.
- [x] "vr3" command - make sure to call show() at the end.  Don't create a new instance if the existing instance has None for parent.
- [x] Dedent `vr3.plot_2d()` node. It was inadvertently located in the `__init__()`subtree.  This did not affect functionality but was not intended.

### CODE REVIEW

**Review by edreamleo — APPROVED** [review]
I'll approve this PR, but you will probably want to update the docstring now that VR3 no longer handles layouts.

**Comment by tbpassin** [comment]
I have no idea what is going to happen here. The PR should have been merged back when I asked and *then* the layout changes could have been merged in.  As it is I don't know how VR3 is going to behave. I also don't know if some of the changes I made have been overridden by changes from the merge of devel.

I would much rather a new branch had been created and my PR merged into it. That would have left my changes alone.  I might have started to work on my branch further and I had no idea that it had been changed in any way. 

Since this PR hasn't been merged into devel, at least I have some some leeway in trying to figure out what's going to work and what isn't.

**Comment by edreamleo** [comment]
@tbpassin I've approved this PR. Please merge it or close it.

**Comment by tbpassin** [comment]
OK, I'll approve it, but I don't see any approval button to use.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your approval.

**Pull request merged**
