### PR TITLE
Add New Command To Execute External Programs

### PR DESCRIPTION
**Pull request by tbpassin**
_@cmd('execute-external-file')_ is added to leoCommands.py.

This command works on Windows and Linux, including when Leo is being run without a terminal.

Note:  This command does not yet work on Macs.  A message is displayed in the Log pane to this effect if the command is tried on a Mac.

### CODE REVIEW

**Review by edreamleo — APPROVED** [review]

**Comment by edreamleo** [comment]
@tbpassin Many thanks for this work.

**Comment by edreamleo** [comment]
I see the following complaints:
```console
mypy-leo
leo\core\leoCommands.py:760: error: Function is missing a return type annotation  [no-untyped-def]
leo\core\leoCommands.py:792: error: Need type annotation for "processor_map" (hint: "processor_map: Dict[<type>, <type>] = ...")  [var-annotated]
leo\core\leoCommands.py:793: error: Need type annotation for "extension_map" (hint: "extension_map: Dict[<type>, <type>] = ...")  [var-annotated]
leo\core\leoCommands.py:818: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:839: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:859: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:870: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:892: error: Function is missing a return type annotation  [no-untyped-def]
leo\core\leoCommands.py:903: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:915: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:935: error: Function is missing a return type annotation  [no-untyped-def]
leo\core\leoCommands.py:941: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:952: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:961: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:990: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:997: error: Function is missing a type annotation  [no-untyped-def]
leo\core\leoCommands.py:1014: error: Cannot determine type of "terminal"  [has-type]
leo\core\leoCommands.py:1025: error: Incompatible types in assignment (expression has type "str", variable has type "List[Any]")  [assignment]
leo\core\leoCommands.py:1027: error: Incompatible types in assignment (expression has type "str", variable has type "List[Any]")  [assignment]
leo\core\leoCommands.py:1029: error: Cannot determine type of "ext"  [has-type]
Found 20 errors in 1 file (checked 261 source files)

flake8-leo
.\leo\core\leoCommands.py:700:22: W605 invalid escape sequence '\R'
.\leo\core\leoCommands.py:732:21: W605 invalid escape sequence '\R'
.\leo\core\leoCommands.py:775:26: W605 invalid escape sequence '\R'
.\leo\core\leoCommands.py:799:52: E701 multiple statements on one line (colon)
.\leo\core\leoCommands.py:874:31: W605 invalid escape sequence '\P'
.\leo\core\leoCommands.py:874:51: W605 invalid escape sequence '\L'
.\leo\core\leoCommands.py:874:59: W605 invalid escape sequence '\l'
pylint-leo
01:18 PM
************* Module leo.core.leoCommands
leo\core\leoCommands.py:700:21: W1401: Anomalous backslash in string: '\R'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
leo\core\leoCommands.py:732:20: W1401: Anomalous backslash in string: '\R'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
leo\core\leoCommands.py:775:25: W1401: Anomalous backslash in string: '\R'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
leo\core\leoCommands.py:874:30: W1401: Anomalous backslash in string: '\P'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
leo\core\leoCommands.py:874:50: W1401: Anomalous backslash in string: '\L'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
leo\core\leoCommands.py:874:58: W1401: Anomalous backslash in string: '\l'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
leo\core\leoCommands.py:865:19: W1510: Using subprocess.run without explicitly set `check` is not recommended. (subprocess-run-check)
leo\core\leoCommands.py:885:19: W1510: Using subprocess.run without explicitly set `check` is not recommended. (subprocess-run-check)
leo\core\leoCommands.py:908:23: W1510: Using subprocess.run without explicitly set `check` is not recommended. (subprocess-run-check)
leo\core\leoCommands.py:903:8: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
leo\core\leoCommands.py:954:23: W1510: Using subprocess.run without explicitly set `check` is not recommended. (subprocess-run-check)
leo\core\leoCommands.py:963:20: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
01:19 PM
```
Please fix them in a new PR. Thanks.

**Comment by tbpassin** [comment]
All right.  Later today or at the latest tomorrow.

**Comment by edreamleo** [comment]
@tbpassin Thanks. These failures are minor, but in the future please run `full-test-leo.cmd` or its equivalent before making a PR.

**Comment by tbpassin** [comment]
Done in PR https://github.com/leo-editor/leo-editor/pull/3169.

I decided to add full annotations.  That was annoying and reduces readability, but I suppose it was worth while.  It did get me to improve the code at a few places.

**Pull request merged**
