### PR TITLE
PR fixes #3727: regex in java importer

### LINKED ISSUE #3727: Java importer bugs with 'interface', (Java importer have regex without capture group, is it normal?)
See PR #3728.

The regex to capture blocks in java seem to have one for **interfaces** (the third one):
```java
    block_patterns = (
        ('class', re.compile(r'.*?\bclass\s+(\w+)')),
        ('func', re.compile(r'.*?\b(\w+)\s*\(.*?\)\s*{')),
        ('interface', re.compile(r'\w*\binterface\w*{')),
```

But, it looks for a word before 'interface', and no separation without spaces between that word and 'interface'.
Stepping in the code while debugging Leo, the sample below does not trigger a match. 

Neither does begenning the interface with:
abc interface Animal {
myInterface Animal

so the following file has the interface inserted at the beginning of the class Pig when doing and @auto node for this sample file: 

```java
interface Animal {
  public void animalSound(); // interface method (does not have a body)
  public void sleep(); // interface method (does not have a body)
}

class Pig implements Animal {
  public void animalSound() {
    // The body of animalSound() is provided here
    System.out.println("The pig says: wee wee");
  }
  public void sleep() {
    // The body of sleep() is provided here
    System.out.println("Zzz");
  }
}

class Main {
  public static void main(String[] args) {
    Pig myPig = new Pig();  // Create a Pig object
    myPig.animalSound();
    myPig.sleep();
  }
}
```

Also, when modifying the file on disk externally, when Leo detects the file change and we choose 'yes' to have it refresh the @auto file from disk, this message is printed in the log and the body does not refresh:
```
setCurrentPosition Invalid position <pos 2176939535872 childIndex: 0 lvl: 1 key: 2176872479232:1.2176872480288:0 class Pig> Commander 2176872740240: 'C:/prog/testmarkdown/testmd1.leo'     
Callers: [
     0: '<module>'
     1: 'main'
     2: 'run_file'
     3: 'run_path'
     4: '_run_module_code'    
     5: '_run_code'
     6: '<module>'
     7: 'run'
     8: 'load'
     9: 'runMainLoop'
    10: 'at_idle_time'        
    11: 'call_handler'        
    12: 'on_idle'
    13: 'on_idle'
    14: 'idle_check_commander'
    15: 'redraw'
    16: 'select'
    17: 'selectHelper'
    18: 'select_new_node'
    19: 'set_body_text_after_select'
]

setCurrentPosition Invalid position <pos 2176939535872 childIndex: 0 lvl: 1 key: 2176872479232:1.2176872480288:0 class Pig> Commander 2176872740240: 'C:/prog/testmarkdown/testmd1.leo'     
Callers: [
     0: '_run_module_as_main'
     1: '_run_code'
     2: '<module>'
     3: 'main'
     4: 'run_file'
     5: 'run_path'
     6: '_run_module_code'
     7: '_run_code'
     8: '<module>'
     9: 'run'
    10: 'load'
    11: 'runMainLoop'
    12: 'at_idle_time'
    13: 'call_handler'
    14: 'on_idle'
    15: 'on_idle'
    16: 'idle_check_commander'
    17: 'redraw'
    18: 'full_redraw'
]

setCurrentPosition Invalid position <pos 2176939535872 childIndex: 0 lvl: 1 key: 2176872479232:1.2176872480288:0 class Pig> Commander 2176872740240: 'C:/prog/testmarkdown/testmd1.leo'     
Callers: [
     0: 'main'
     1: 'run_file'
     2: 'run_path'
     3: '_run_module_code'
     4: '_run_code'
     5: '<module>'
     6: 'run'
     7: 'load'
     8: 'runMainLoop'
     9: 'at_idle_time'
    10: 'call_handler'
    11: 'on_idle'
    12: 'on_idle'
    13: 'idle_check_commander'
    14: 'redraw'
    15: 'selectPosition'
    16: 'select'
    17: 'selectHelper'
    18: 'select_new_node'
    19: 'set_body_text_after_select'
]

setCurrentPosition Invalid position <pos 2176939535872 childIndex: 0 lvl: 1 key: 2176872479232:1.2176872480288:0 class Pig> Commander 2176872740240: 'C:/prog/testmarkdown/testmd1.leo'     
Callers: [
     0: '_run_module_as_main'
     1: '_run_code'
     2: '<module>'
     3: 'main'
     4: 'run_file'
     5: 'run_path'
     6: '_run_module_code'
     7: '_run_code'
     8: '<module>'
     9: 'run'
    10: 'load'
    11: 'runMainLoop'
    12: 'at_idle_time'
    13: 'call_handler'
    14: 'on_idle'
    15: 'on_idle'
    16: 'idle_check_commander'
    17: 'redraw'
    18: 'selectPosition'
]
```

Lastly, Java and ~ini~ importers have regex without capture groups, is it normal?

### PR DESCRIPTION
**Pull request by edreamleo**
See #3727.

- [x] Fix the regex for `interface`, following the pattern of the other regexes.
- [x] Change the corresponding unit tests.
- [x] Add `TestJava.test_round_trip`.
   It passes *only* with a hack acknowledging that all bodies end with a single newline.
   See the long comment below for why this hack is justified, at least for now.

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex This PR is ready for review.

**Review by boltex — COMMENTED** [review]
With this fix to the java importer, the 'interface' section is now properly read and created in the outline of the @auto node. 

But the other 2 bugs still remain: newlines are 'eaten' when writing java @auto nodes to file, and when a file change is detected and the outline is refreshed from disk, Leo's refresh cycle fails with this error in the terminal:

```
setCurrentPosition Invalid position <pos 2732608376064 childIndex: 0 lvl: 1 key: 2732608548432:1.2732608548608:0 interface Animal> Commander 2732608351696: 'C:/prog/testmarkdown/testmd1.leo'
Callers: [
     0: '_run_module_as_main'
     1: '_run_code'
     2: '<module>'
     3: 'run'
     4: 'load'
     5: 'runMainLoop'
     6: 'at_idle_time'
     7: 'call_handler'
     8: 'on_idle'
     9: 'on_idle'
    10: 'idle_check_commander'
    11: 'redraw'
    12: 'select'
    13: 'selectHelper'
    14: 'select_new_node'
    15: 'set_body_text_after_select'
]

setCurrentPosition Invalid position <pos 2732608376064 childIndex: 0 lvl: 1 key: 2732608548432:1.2732608548608:0 interface Animal> Commander 2732608351696: 'C:/prog/testmarkdown/testmd1.leo'
Callers: [
     0: '_run_module_as_main'
     1: '_run_code'
     2: '<module>'
     3: 'run'
     4: 'load'
     5: 'runMainLoop'
     6: 'at_idle_time'
     7: 'call_handler'
     8: 'on_idle'
     9: 'on_idle'
    10: 'idle_check_commander'
    11: 'redraw'
    12: 'full_redraw'
]

setCurrentPosition Invalid position <pos 2732608376064 childIndex: 0 lvl: 1 key: 2732608548432:1.2732608548608:0 interface Animal> Commander 2732608351696: 'C:/prog/testmarkdown/testmd1.leo'
Callers: [
     0: '_run_module_as_main'
     1: '_run_code'
     2: '<module>'
     3: 'run'
     4: 'load'
     5: 'runMainLoop'
     6: 'at_idle_time'
     7: 'call_handler'
     8: 'on_idle'
     9: 'on_idle'
    10: 'idle_check_commander'
    11: 'redraw'
    12: 'selectPosition'
    13: 'select'
    14: 'selectHelper'
    15: 'select_new_node'
    16: 'set_body_text_after_select'
]

setCurrentPosition Invalid position <pos 2732608376064 childIndex: 0 lvl: 1 key: 2732608548432:1.2732608548608:0 interface Animal> Commander 2732608351696: 'C:/prog/testmarkdown/testmd1.leo'
Callers: [
     0: '_run_module_as_main'
     1: '_run_code'
     2: '<module>'
     3: 'run'
     4: 'load'
     5: 'runMainLoop'
     6: 'at_idle_time'
     7: 'call_handler'
     8: 'on_idle'
     9: 'on_idle'
    10: 'idle_check_commander'
    11: 'redraw'
    12: 'selectPosition'
]

```

**Comment by boltex** [comment]
Perhaps those 2 other bugs are not related to the regex, and so I should accept this pull request? If you  advise so I will do it. no problem.

**Comment by boltex** [comment]
@edreamleo Just want to not in this thread also that maybe the missing newlines when _writing_, are in fact newlines that should have been added in when _reading_, so that when writing, it would be ok! :)

**Comment by edreamleo** [comment]
@boltex Thanks for your comments. We can leave the PR open for now: I'll review the read logic.

**Comment by edreamleo** [comment]
@boltex **tl;dr:** Please approve this PR :-)  The round-trip issue is extraordinarily complex, but I suspect everything is working well enough.

We can zoom about this issue if you like.

**Analysis**

Leonistas are not complaining about `@auto`. That's significant because there is no separate code for importing Java code. The base `Importer` class does everything except define the `block_patterns` list of regexes.

The new unit test in this PR passes only because of a hack to the expected result. However, the reason why the hack is necessary is clear.  Both `Importer.compute_body` and the `handle_block_with_children` function *regularizes* trailing whitespace from the imported nodes.

Regularizing trailing whitespace ruins "perfect import", but is that really such a bad thing? 

As far as the crash (invalid Position) goes, you *might* have made some kind of mistake in creating your `@auto` node. Everything works for me with the following  `@auto` node. You should be able to copy the node from the details and paste it into an existing .leo file. Change the path as necessary. 

<details>

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: https://leo-editor.github.io/leo-editor/leo_toc.html -->
<leo_file xmlns:leo="https://leo-editor.github.io/leo-editor/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<vnodes>
<v t="ekr.20231225025443.1"><vh>@auto c:\test\test_round_trip.java</vh>
<v t="ekr.20231225095735.1"><vh>class Main</vh>
<v t="ekr.20231225095735.2"><vh>func main</vh></v>
<v t="ekr.20231225095735.3"><vh>func myMethod</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20231225025443.1">@others
@language java
@tabwidth -4
</t>
<t tx="ekr.20231225095735.1">public class Main {
    @others
}
</t>
<t tx="ekr.20231225095735.2">public static void main(String[] args) {
    myMethod();
}
</t>
<t tx="ekr.20231225095735.3">static void myMethod() {
    System.out.println("I just got executed!");  // changed.
}
</t>
</tnodes>
</leo_file>
```

</details>

**Summary**

Nobody is complaining except you. You have a special dispensation to do so, but I think all is well.

If we decide there is a real problem let's leave it for after LeoJS 1.0 :-)

**Review by boltex — APPROVED** [review]
No problem.

**Pull request merged**
