### PR TITLE
Add current line highlighting; Make sure that flashing matching 

### PR DESCRIPTION
**Pull request by tbpassin**
bracket does not kill line highlighting.

### CODE REVIEW

**Comment by tbpassin** [comment]
Note that an item is added to the help-for menu and a new help-for-highlight-current-line command is added.

**Review by edreamleo — CHANGES_REQUESTED** [review]
Please base this PR on devel.  ekr-unit-test can't be merged into devel until 6.5.

**Comment by tbpassin** [comment]
I thought the plan was for line highlighting to go into 6.5, not 6.4. If you want to change that, let me know and I'll redo the PR.

**Comment by edreamleo** [comment]
On Mon, Sep 13, 2021 at 5:24 PM tbpassin ***@***.***> wrote:

> I thought the plan was for line highlighting to go into 6.5, not 6.4. If
> you want to change that, let me know and I'll redo the PR.
>

I think the code can go into 6.4.

Edward

**Comment by tbpassin** [comment]
OK, I have put in a PR based on devel.  Let's cancel this one.

**Pull request closed without merging**
