### PR TITLE
Fix @image directive in VR3

### PR DESCRIPTION
**Pull request by tbpassin**
Bug fix for Viewrendered3: @image directive now works when there is a previous @language directive in the node.

Docstring edits.  Version to 3.02.

### CODE REVIEW

**Comment by edreamleo** [comment]
Thanks, Tom, for this work. The code itself looks good.

However, the @file line should be @file ../plugins/viewrendered3.py. That way it will open properly from LeoPyRef.leo. Did you test that?

**Comment by tbpassin** [comment]
Edward, I didn't test it that way.  I should revise my development tree, and I'll look at that.  Currently I develop in a separate location, and copy the file to the GitHub directory with a Leo command (linked to the F5 key).  I have never actually changed LeoPyRef.  In fact, I didn't know that development should be done in it.

Why don't you go ahead and make that change, and I'll adjust my own development tree for next time.

**Comment by edreamleo** [comment]
On Wed, Feb 17, 2021 at 1:35 PM tbpassin <notifications@github.com> wrote:

> Edward, I didn't test it that way. I should revise my development tree,
> and I'll look at that. Currently I develop in a separate location, and copy
> the file to the GitHub directory with a Leo command (linked to the F5 key).
> I have never actually changed LeoPyRef. In fact, I didn't know that
> development should be done in it.
>
You can develop any way you like, provided the result is compatible with
LeoPyRef.leo. Leo supports using a private copy of LeoPyRef.leo, called
leoPy.leo.

> Why don't you go ahead and make that change, and I'll adjust my own
> development tree for next time.
>
Will do.

Edward

**Comment by edreamleo** [comment]
I am closing this PR. PR #1819 replaces it.

**Comment by edreamleo** [comment]
On Thu, Feb 18, 2021 at 6:45 AM Edward K. Ream <edreamleo@gmail.com> wrote:

On Wed, Feb 17, 2021 at 1:35 PM tbpassin <notifications@github.com> wrote:
>

> Why don't you go ahead and make that change, and I'll adjust my own
development tree for next time.

I have just merged the ekr-vr3 branch into devel. See PR #1820
<https://github.com/leo-editor/leo-editor/pull/1820>.

This turned out to be a substantial project. In future I'll insist that PR
authors do the required work:

- Create a branch off of devel, not just a private devel branch.
- Ensure that their work is compatible with leoPy.leo (LeoPyRef.leo).
- Ensure that pylint is happy.

I corrected several pylint complaints concerning the module-level
docstring. It now starts with `r"""`, not `"""`.

One pylint complaints remains in devel:

************* Module leo.plugins.viewrendered3
leo\plugins\viewrendered3.py:2554:12: W0601:
Global variable '_in_code_block' undefined at the module level
(global-variable-undefined)

This may be a real bug.  Changing "global" to "nonlocal" did remove the
complaint, but I don't think that fix is valid. Please look into this.

Edward

**Comment by tbpassin** [comment]
Let me see if I understand things correctly here.  After I make changes to - in this case, VR3, and copy the changed file into my local github tree, I should open LeoPy.leo in Leo and see that my new version is there correctly.  

Then it would be wise for me to run pylint on the file **as it is contained in LeoPy.leo**.  This would verify that nothing has gone awry.

Should I then commit LeoPy.leo as well as the actual VR3 file?  So far I have not been committing LeoPy.leo.  I've been a little hesitant to do this because sometimes it can't find certain files to load (I think I remember LeoCloud or some such) and I was concerned they might become corrupted if that version of LeoPy.leo were saved and committed. (It's possible that this behavior actually happened with LeoDocs.leo instead, but it left me apprehensive about saving and committing LeoPy.leo).

About my own branch of _devel_, I fetched and merged and committed the current state of Leo's _devel_ branch into my own just before I issued the PR.  Isn't this the preferred way?  (I also had fetched devel into my branch in which I had developed my changes to VR3, but I don't recall if I had merged and committed or not.)

**Comment by edreamleo** [comment]
On Thu, Feb 18, 2021 at 1:10 PM tbpassin <notifications@github.com> wrote:

> Let me see if I understand things correctly here.
>
Thanks for asking.

> After I make changes to - in this case, VR3, and copy the changed file
> into my local github tree, I should open LeoPy.leo in Leo and see that my
> new version is there correctly.
>
Let's start at the beginning.  First, create a branch, based on devel, in a
clone of leo-editor.

Next, work in this branch. You don't want to be copying files if you can
possibly help it.

Next, do the work in LeoPy.leo, using Leo, of course.

> Then it would be wise for me to run pylint on the file *as it is
> contained in LeoPy.leo*. This would verify that nothing has gone awry.
>
Yes. Choose the @file node and choose Leo's pylint command.

> Should I then commit LeoPy.leo as well as the actual VR3 file?
>
No. LeoPy.leo is your private copy.

.gitignore contains these lines:

leo/core/LeoPy.leo
leo/core/leoPy.leo

so the capitalization of your private copy doesn't matter.

> So far I have not been committing LeoPy.leo.
>
Nor should you ever do so.

> About my own branch of *devel*, I fetched and merged and committed the
> current state of Leo's *devel* branch into my own just before I issued
> the PR. Isn't this the preferred way?
>
The problem is that PR #1819
<https://github.com/leo-editor/leo-editor/pull/1819> wants to merge
tbpassin:devel into leo-editor:devel.

Instead, you want to merge my-branch into devel. It should look like PR
#1820 <https://github.com/leo-editor/leo-editor/pull/1820>.

*Summary*

Clone leo-editor into your own local repo, work in leoPy.leo, create a
branch based on devel, push your work to origin, and create a PR that looks
more like #1820 than #1819.

These are expected growing pains. Don't worry about it. If you have
problems following this workflow please ask for help.

Edward

**Comment by tbpassin** [comment]
> 
> On Thu, Feb 18, 2021 at 1:10 PM tbpassin ***@***.***> wrote: Let me see if I understand things correctly here.
> Thanks for asking.
> After I make changes to - in this case, VR3, and copy the changed file into my local github tree, I should open LeoPy.leo in Leo and see that my new version is there correctly.
> Let's start at the beginning. First, create a branch, based on devel, in a clone of leo-editor. Next, work in this branch. You don't want to be copying files if you can possibly help it. Next, do the work in LeoPy.leo, using Leo, of course.

I've been doing this. I have my own clone of the Leo repo.  When I start work on a new feature, I update from Leo's _devel_ to my clone, then create a branch based on *my* updated _devel_ branch.  Let's call my new branch _vr3-feature1_.

I do the development in _vr3-feature1_.  When I am ready to do a PR, what I have done recently is:

1. Update  _vr3-feature1_ from leo's _devel_ . My intent is to avoid inadvertently asking to merge any old versions of other files in _devel_ that might have been updated since I created the new branch _vr3-feature1_.
2.  Commit everything in my _vr3-feature1_ branch if not already done.
3. Then I update my own _devel_  from_vr3-feature1_  branch and make a PR for that.

I think you are telling me to replace step 3 by step 3a:

3a. Generate the PR from my (updated-from-current-_devel_) _vr3-feature1_ branch.

I can do that.  It would be easier if I could skip updating my branch from Leo's _devel_ branch.  Would that work, even if Leo's _devel_ branch had say 50 new updates since I started my _vr3-feature1_ branch?

**Pull request closed without merging**
