### PR TITLE
PR for #3404: save session data to global cache

### PR DESCRIPTION
**Pull request by edreamleo**
See #3409.

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex @tbpassin Please review.  Thanks.

**Review by tbpassin — COMMENTED** [review]
leoSessions.py, line 83 - 
```
except KeyError:
            pass  # Not a user error.
```
I'd like to g.es() a message for this case; e.g. `Cannot find a previous session to load`.

**Comment by edreamleo** [comment]
@tbpassin It's a close call, but I suppose the extra message won't be too annoying :-)

**Comment by edreamleo** [comment]
@tbpassin Done in rev 9c48fb4. Please approve the PR :-)

**Review by tbpassin — APPROVED** [review]

**Comment by edreamleo** [comment]
@tbpassin Thanks for the approval.

**Pull request merged**
