### PR TITLE
PR for #3988: crash in pygments colorizer

### PR DESCRIPTION
**Pull request by edreamleo**
See #3988.

**Long standing bugs that affect LeoJS**

- [x] Fix long-standing bug in `BaseColorizer.useSyntaxColoring`.

**Newly-discovered bugs that do not affect LeoJS**

- `@nocolor` could crash pygments.
- The pygments colorizer does not recolor when an `@language` directive changes.
  The `JEditColorizer` class works as desired via the Leo-specific matcher `match_at_language`.
  Similarly, for matchers for `@killcolor`, `@color`, etc.

**Other changes**

- [x] Make `PatchedLexer` a subclass of `pygments.DelegatingLexer`.
   This change *might* be the only change needed to fix the original issue.
- [x] Add a guard to `BaseColorizer.setTag`.
- [x] Leo's `recolor` command now calls `colorizer.force-recolor` as a hook for the pygments colorizer.
   This forces a full recolor. It's not as smooth as the jEdit colorizer, but it's an improvement.
- [x] All coloring unit tests now test both the jEdit and pygments colorizers.

### CODE REVIEW

**Review by tbpassin — CHANGES_REQUESTED** [review]
[I read the issue that ekr filed with the pygments projects so I know that some of these changes are about.]
_leoColorizer.py_
1. Line 18, typo in comment. Should read `# Third-party tools`.
2. Line 828, typo in comment.  Change _enabgled_ to read _enabled_.
3. Line 3187: `class PatchedLexer(DelegatingLexer, lexer.__class__):`
This is probably just my ignorance about multiple inheritance, but now calls that used to be handled by _lexer_ are now supposed to be handled by _DelegatingLexer_. What makes that happen? Is it just because _DelegatingLexer_ comes first in the constructor?

**Comment by edreamleo** [comment]
@tbpassin The last rev fixes both typos.

Point 3: The code just follows the pattern [here](https://pygments.org/docs/lexerdevelopment/#delegating-lexer). I know nothing more :-) The revised unit tests cover all languages known to pygments w/o crashes, so that probably suffices.

**Review by tbpassin — COMMENTED** [review]
_leoColorizer.py_, line 3040 :
 `def force_recolor(self)`

I don't see how this method actually performs a recolor.  It picks up any language or color directive changes, but where does it actually do recoloring?  Or does it just re-initialize the colorizer for the next time it gets triggered? If it doesn't actually recolor, it should be named more clearly.  

I presume that a recolor will happen on any change to  a node's body.  So changing an `@language` or `@color` directive would trigger a recolor.  Therefore I can understand that the method only needs to reset the language or color states of the colorizer.  But in that case it's not actually doing any recoloring.

Also, if the language were to change, wouldn't that require the colorizer to use a different lexer?  I don't see where that happens.

**Comment by edreamleo** [comment]
@tbpassin I don't know exactly why `force_recolor` works, but it does. It's a slight modification of `pyg_c.recolor`.

The pygments colorizer is tricky. It contains numerous hacks, including code borrowed (with attribution) from the Jupyter project. Please don't ask me to explain the details :-)

**Comment by edreamleo** [comment]
@tbpassin Please approve the PR. Merging it will help further testing.

**Review by tbpassin — APPROVED** [review]

**Comment by edreamleo** [comment]
@boltex The changes to `BaseColorizer.useSyntaxColoring` are the only changes that should affect LeoJS.

**Pull request merged**
