### PR TITLE
PR for #3005: load-leo.html

### PR DESCRIPTION
**Pull request by edreamleo**
See #3005.

- [x] Rewrite  `load-leo.html`, referencing `vscode.dev`.

### CODE REVIEW

**Comment by edreamleo** [comment]
@tbpassin @LewisNeal This PR is ready for review. I would appreciate your comments and testing.

**Review by tbpassin — CHANGES_REQUESTED** [review]
1. Loading the link in README.md for load-leo.html into the browser fails.  This is because load-leo.html is looking for the two newly copied scripts in a _scripts_ directory:
 ```
<script type="text/javascript" src="scripts/upclick-min.js"></script>
<script type="text/javascript" src="scripts/jquery.min.js"></script>
```
but they are actually in a _docs_ directory.

2. Why are these scripts in two places, _leo-editor/docs_ and _leo-editor/tools/webroot_?  They should only be in one location.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your testing, Thomas.

I don't know why the scripts are in two places. Perhaps they get copied as part of the distribution process.

Good catch about the scripts directory. I'll create the directory and test for myself.

**Comment by edreamleo** [comment]
Still no joy after moving the .js file and deploying to Leo's website.

I get `405 Not Allowed` when trying to upload a local file.

Nothing happens when I try to open https://github.com/leo-editor/leo-editor/raw/master/leo/doc/LeoDocs.leo

**Comment by tbpassin** [comment]
I don't know how this can be tested on the github.io site without being in the branch that gets deployed by the io machinery.  I assumed that the directory structure on the .io site is the same as the file tree.  If that's not right the relative path to the scripts would have to be adjusted.

I also don't know how to examine the directory structure on the .io site since it's only addressable by a browser AFAIK.

OTOH, not being able to upload a local outline is not the same problem as the original issue.

Personally I have never saw this particular capability as making much sense.  Someone who doesn't know Leo would look at the generated page and just see an expandable tree like a million others.  What makes this Leo version different?  One can't do anything with it.  Plus it looks crude, which is not a strong selling point.

A Leo user wouldn't have much use for it either.  So I would just retire the link altogether.

**Comment by edreamleo** [comment]
@tbpassin Great minds thinking alike! The way-way better alternative is vs-code in the browser! https://vscode.dev/

Works only with Chrome and Edge. Also, leoInteg doesn't yet work with vscode.dev, but when it does work it will blow the old page away.

**Pull request merged**
