### PR TITLE
PR: Fix minor flake8 complaints

### PR DESCRIPTION
**Pull request by edreamleo**
- [x] Fix straightforward flake8 warnings.
- [x] Add flake8 suppressions to setup.cfg for difficult/dangerous flake8 warnings.

### CODE REVIEW

**Comment by edreamleo** [comment]
@vitalije I am unsure of the proper annotation for the newly created defs in leoFileCommands.py.

mypy complains about the 'x' arg to the new findNode and pv functions. Do you have any suggestions?

**Comment by vitalije** [comment]
I can't find the definition of `pv`. And `findNode`' takes an argument of type `str` and returns `VNode` instance.

**Comment by vitalije** [comment]
Oh, I've found it. It is the same as `findNode`.

**Comment by edreamleo** [comment]
Changing the annotation of 'x' to 'str' in the two functions generates these complaints:
```console
leo\core\leoFileCommands.py:1090: error: Argument 1 to "findNode" has incompatible type "VNode"; expected "str"  [arg-type]
leo\core\leoFileCommands.py:1091: error: Argument 1 to "findNode" has incompatible type "VNode"; expected "str"  [arg-type]
leo\core\leoFileCommands.py:1199: error: Argument 1 to "pv" has incompatible type "VNode"; expected "str"  [arg-type]
leo\core\leoFileCommands.py:1200: error: Argument 1 to "pv" has incompatible type "VNode"; expected "str"  [arg-type]
```
Changing the annotations of 'x' to 'VNode' generates these complaints:
```
leo\core\leoFileCommands.py:1086: error: No overload variant of "get" of "dict" matches argument types "VNode", "VNode"  [call-overload]
leo\core\leoFileCommands.py:1086: note: Possible overload variants:
leo\core\leoFileCommands.py:1086: note:     def get(self, str) -> VNode
leo\core\leoFileCommands.py:1086: note:     def [_T] get(self, str, Union[VNode, _T]) -> Union[VNode, _T]
leo\core\leoFileCommands.py:1196: error: No overload variant of "get" of "dict" matches argument types "VNode", "VNode"  [call-overload]
leo\core\leoFileCommands.py:1196: note: Possible overload variants:
leo\core\leoFileCommands.py:1196: note:     def get(self, str) -> VNode
leo\core\leoFileCommands.py:1196: note:     def [_T] get(self, str, Union[VNode, _T]) -> Union[VNode, _T]
```

**Comment by vitalije** [comment]
Correct annotation for argument is `str` and return value is of type `VNode`. The type checker complains due to the fact that the algorithm uses Python ability to change the type of the members in the list. Initially, all `vnodes` restored from the database have their `parents` and `children` fields set to list of strings (only gnx is stored instead of the `vnode` instances). In the above mentioned lines, those fields ( `children` and `parents`) are transformed from the lists of strings into the list of `VNodes`. However, type checker can't understand this transformation and it warns that we're trying to use `vnode` instances as arguments to `findNode` which expects only strings. 

The code can be changed to keep the track of children and parent `gnx` keys during loading in the separate dictionary and not directly in the fields of `VNode` instances, but IMO this would unnecessarily complicate the code just to make type checker happy. I don't know if it is possible to silence these few warnings using some comments in the above lines or not. If not I suggest just to leave the annotation to `Any`. 

Assuming that no other thread is reading from the `gnxDict` during the execution of these methods, the code is safe. At the end of the method, there will be no `VNode` instances with `children` and `parents` fields that contain anything else but `VNode` instances. Only during the execution of these methods, temporarily, they will contain strings in those fields.

**Comment by vitalije** [comment]
Just to illustrate what is happening in the `retrieveVnodesFromDb` method:

https://github.com/leo-editor/leo-editor/blob/01dc721d2680ce4b3aef045532c63b5ff73dabd8/leo/core/leoFileCommands.py#L1058-L1071

Variables `children` and `parents` are retrieved from the database as a strings (line 1059). They contain just `gnx` fields of each child/parent separated by space character. At lines 1067 and 1068, fields of newly created `VNode` instance `v.parents` and `v.children` are set to list of strings. Then, after all `Vnode` instances are recreated, hence all of them are now values of the `fc.gnxDict`, we can replace strings with the corresponding `VNode` instances in the lines 1090-1091

https://github.com/leo-editor/leo-editor/blob/01dc721d2680ce4b3aef045532c63b5ff73dabd8/leo/core/leoFileCommands.py#L1090-L1091

The flow of the operation consists of two separated but tightly connected phases. In the first phase, lines 1058-1071 we're just creating vnodes and after we have created all of the nodes, in the second phase we restore the links between them as they were when the outline was saved. It is necessary for the first phase to be completed before the second phase starts. Otherwise, we could bump into the problem trying to link not yet existing nodes.

Although the type checker rightly complains, the code is perfectly legal Python code.

**Comment by edreamleo** [comment]
@vitalije Thanks for your comments. I'll add the correct annotation, with a `# type:ignore` telling mypy not to worry.

**Pull request merged**
