### PR TITLE
1. Open external editor commands work with spaces in path;

### PR DESCRIPTION
**Pull request by tbpassin**
2. Removed openwith_rclick for external editor because Open With Editor already does same thing more flexibly.
3. Rename "Open In <editor>" to "Open With <editor>".
4. Only show editor filename, not entire path.

Pylint: 10.0/10.

### CODE REVIEW

**Review by edreamleo — APPROVED** [review]
Thanks for this. I did something similar, but your code looks better.

There is a merge conflict, but I think I can handle it.

**Comment by tbpassin** [comment]
Thanks.  Funny about the merge conflict.  When I issued the PR, Github said it could be merged automatically.

**Comment by edreamleo** [comment]
@tbpassin I think what happened is that I merged my branch into devel after you created your branch. My apologies for the confusion. I didn't realize that you were going to work on this issue.

**Comment by tbpassin** [comment]
I thought that might be it.  I hadn't planned on working the issue, since I knew you had just been working on the same file and would be more familiar with the ends and outs.  But then you wrote how you didn't want to think about it any more - I heard some level of frustration - and I looked a little more at the code out of curiosity.  So I just went ahead.

BTW, somehow some lines that added quoting outside my new function got left in.  They aren't needed any more since that function does the same thing.  Sometime after 6.4b1 (if I remember to do it), I'll take them out with a PR.

**Comment by edreamleo** [comment]
@tbpassin Thanks for these comments. There is no rush :-)

**Pull request merged**
