### PR TITLE
Finalize New Layouts;  Add help-for-layouts and layout-show-layouts Commands

### PR DESCRIPTION
**Pull request by tbpassin**
- [x] Removed "legacy" and "fallback" layouts;
- [x] Added mapping of command names and docstrings;
- [x] Improved logic for choosing layout if layout setting is missing or invalid;
- [x] Created command 'layout-show-layouts'.
- [x] Created menu item for above in menu Settings/Show Settings
- [x] Created "help-for-layouts" command;
- [x] Created menu item in Help/Open help topics menu for the "help-for-layouts" command;
- [x] Editorial clarifications for layout docstrings;
- [x] Added some type annotations;
- [x] (qt_layout) pylint: no messages;
- [x] (qt_layout) mypy: no messages;
- [x] pytest: `932 passed, 2 skipped, 2 warnings in 26.10s`; [Note: qt_layout has no unit tests]

### CODE REVIEW

**Review by edreamleo — CHANGES_REQUESTED** [review]
mypy issues three complaints in the `tbpassin:tbp-layout-display-docstrings-2` branch.

I have not figured out how to create a PR in that branch.  To fix these complaints, please make the following two changes:

-from leo.core.leoQt import QtWidgets, Orientation, QtCore
+from leo.core.leoQt import QtWidgets, Orientation, QtCore, QtObject, QSplitter
 
-QW = TypeVar('QW', bound=QtWidgets.QWidget)
+QW = TypeVar('QW', QtObject, QSplitter)

**Comment by tbpassin** [comment]
Where is the mypy config file you are using?  My run of mypy didn't throw up any suggestions.  I'll make the changes but would like to get the same results as you do.

**Comment by tbpassin** [comment]
> -QW = TypeVar('QW', bound=QtWidgets.QWidget)
> +QW = TypeVar('QW', QtObject, QSplitter)

Why do you want to generalize to QtObject?  All QWidgets are QtObjects, are they not?  And all QSplitters are QWidgets too.  So the original QW includes all types derived from QWidget.  Remember, the purpose of the `bound` construction is to allow derived types, which of course we use.

> -from leo.core.leoQt import QtWidgets, Orientation, QtCore
> +from leo.core.leoQt import QtWidgets, Orientation, QtCore, QtObject, QSplitter

The only place where a QSplitter is specifically used is

`splitter = QtWidgets.QSplitter(self)`

That's a perfectly legal type that mypy shouldn't object to.

What mypy objects to (at least with my configuration file) is this kind of construction:

```
QWidget = QtWidgets.QWidget
widget = QWidget()
```

That is why I started to use "QW" written this way:

`QW = TypeVar('QW', bound=QtWidgets.QWidget)`

I don't want to make the changes you are requesting until I have a better understanding of why your runs of mypy think there is a problem.  Your proposal weakens type checking for no benefit, so far as I can see.

**Comment by tbpassin** [comment]
Maybe this is a python version thing.  I'll type check with Python 3.9.  We are still supporting 3.9, aren't we?

**Comment by tbpassin** [comment]
That's bizarre.  Using Python 3.9, mypy started checking all the files, not just qt_layouts.py.  It spooled out hundreds of complaints about LeoGlobals before I terminated the session. 

So that won't work, type checking with Python 3.9.  OTOH, I now remember you said that it's fine to type check only with Python 3.12, which makes sense to me as I think on it.

**Comment by edreamleo** [comment]
@tbpassin

`leo-editor/.mypy.ini` contains the settings I use. LeoPyRef contains `@edit ../../.mypy.ini`

mypy complains (for me) without the change I suggest. At lines 477, 498 and 532 the error is:

`error: Incompatible types in assignment (expression has type "QObject", variable has type "QW")  [assignment]`

**Comment by tbpassin** [comment]
I am at a loss here.  I just upgraded mypy to the latest version, and now trying to check qt_layout.py is giving huge numbers of mypy messages about many other Leo files.  Before I upgraded mypy this didn't happen.

Furthermore, some of the error messages are `[attr-defined]`, which I thought was disabled in mypy.ini.

It looks like mypy is following a lot of imports, perhaps.  Here's the mypy output, highly truncated.  at least it doesn't seem to have found errors in Qt_layout.py:

```
mypy: qt_layout.py
C:\Tom\git\leo-editor\leo\external\npyscreen\wgwidget_proto.py:50: error: "_LinePrinter" has no attribute "parent"  [attr-defined]
C:\Tom\git\leo-editor\leo\external\npyscreen\eveventhandler.py:41: error: "EventHandler" has no attribute "register_for_event"  [attr-defined]
C:\Tom\git\leo-editor\leo\external\npyscreen\eveventhandler.py:63: error: Module has no attribute "ReferenceError"  [attr-defined]
leoGlobals.py:58: error: Module "types" has no attribute "Module"  [attr-defined]
leoGlobals.py:59: error: Module "leo.core" has no attribute "LeoGlobals"  [attr-defined]
leoGlobals.py:62: error: Module "leo.core.leoGui" has no attribute "LeoFrame"; maybe "leoFrame"?  [attr-defined]
leoGlobals.py:218: error: "Callable[..., Any]" has no attribute "__func_name__"  [attr-defined]
leoGlobals.py:219: error: "Callable[..., Any]" has no attribute "is_command"  [attr-defined]
leoGlobals.py:220: error: "Callable[..., Any]" has no attribute "command_name"  [attr-defined]
leoGlobals.py:261: error: "Callable[[LeoKeyEvent], None]" has no attribute "__func_name__"  [attr-defined]
leoGlobals.py:271: error: "Callable[..., Any]" has no attribute "is_command"  [attr-defined]
leoGlobals.py:272: error: "Callable[..., Any]" has no attribute "command_name"  [attr-defined]
leoGlobals.py:322: error: "Callable[[LeoKeyEvent], None]" has no attribute "__func_name__"  [attr-defined]
leoGlobals.py:548: error: "None" has no attribute "bind"  [attr-defined]
leoGlobals.py:582: error: "None" has no attribute "title"  [attr-defined]
leoGlobals.py:583: error: "None" has no attribute "withdraw"  [attr-defined]
leoGlobals.py:585: error: "None" has no attribute "pack"  [attr-defined]
leoGlobals.py:591: error: "None" has no attribute "destroy"  [attr-defined]
leoGlobals.py:601: error: "None" has no attribute "geometry"  [attr-defined]
leoGlobals.py:602: error: "None" has no attribute "lift"  [attr-defined]

......

leoAst.py:3483: error: "AST" has no attribute "value"  [attr-defined]
leoAst.py:3493: error: "AST" has no attribute "keys"  [attr-defined]
leoAst.py:3493: error: "AST" has no attribute "values"  [attr-defined]
leoAst.py:3496: error: "AST" has no attribute "keys"  [attr-defined]
leoAst.py:3497: error: "AST" has no attribute "keys"  [attr-defined]
leoAst.py:3497: error: "AST" has no attribute "values"  [attr-defined]
leoAst.py:3511: error: "AST" has no attribute "key"  [attr-defined]
leoAst.py:3513: error: "AST" has no attribute "value"  [attr-defined]

....

leoFind.py:218: error: "Bunch" has no attribute "suboutline_only"  [attr-defined]
leoFind.py:219: error: "Bunch" has no attribute "whole_word"  [attr-defined]
leoFind.py:622: error: "Commands" has no attribute "quicksearch_controller"  [attr-defined]
leoFind.py:893: error: "LeoGui" has no attribute "openFindDialog"  [attr-defined]
leoFind.py:901: error: "LeoGui" has no attribute "openFindDialog"  [attr-defined]
leoFind.py:2316: error: "Bunch" has no attribute "p"  [attr-defined]
leoFind.py:2564: error: "LeoGui" has no attribute "get_focus"  [attr-defined]

....

leoApp.py:2193: error: "str" has no attribute "val"  [attr-defined]
leoApp.py:2197: error: "dict[str, str]" has no attribute "name"  [attr-defined]
leoApp.py:2205: error: "str" has no attribute "stroke"  [attr-defined]
leoApp.py:2422: error: "LeoApp" has no attribute "recentFilesManager"  [attr-defined]
leoApp.py:2622: error: "LeoApp" has no attribute "recentFilesManager"  [attr-defined]
leoApp.py:3028: error: "LeoApp" has no attribute "recentFilesManager"  [attr-defined]
leoApp.py:3138: error: "Commands" has no attribute "refreshFromDisk"  [attr-defined]
leoApp.py:3260: error: "Commands" has no attribute "refreshFromDisk"  [attr-defined]
leoApp.py:3646: error: "Commands" has no attribute "deleteOutline"  [attr-defined]

....
C:\Tom\git\leo-editor\leo\plugins\qt_gui.py:2158: error: QWidget? has no attribute "leo_master"  [attr-defined]
C:\Tom\git\leo-editor\leo\plugins\qt_gui.py:2168: error: QWidget? has no attribute "setStyleSheet"  [attr-defined]
Found 1353 errors in 25 files (checked 1 source file)
mypy: finished
```

mypy version: 1.13.0
Python version: 3.12.3

**Comment by tbpassin** [comment]
> This order might cause problems for you unless you run mypy_leo.py from Leo's top-level directory.

I run it on a single @file tree as a minibuffer command and that has always worked in the past.  If it doesn't there is something wrong with the mypy command.

**Comment by tbpassin** [comment]
> mypy complains (for me) without the change I suggest. At lines 477, 498 and 532 the error is:
> 
> `error: Incompatible types in assignment (expression has type "QObject", variable has type "QW") [assignment]`

The code at line 477 is:

```
        for kid in self.children():
            if kid.objectName() == name:   # <=== 477
```
"kid" will always be a QWidget or descendant.  It's often going to be a `leo.plugins.viewrendered.ViewRenderedController` or a `leo.plugins.viewrendered.ViewRenderedController3`

Both of those are QWidgets.  Probably this change would satisfy mypy but I can't test it as yet:

`for kid:QW in self.children():`

**Comment by edreamleo** [comment]
@tbpassin Running mypy on a single file is unreliable. I don't know what the problem is and I can't diagnose it remotely.

Please make the change I suggested. I'll then approve and merge the PR. After that I'll deal with any further problems.

**Comment by tbpassin** [comment]
All right, I've pushed some changes.  At least one of your requested changes didn't work .  In fact I tried a lot of apparently obvious annotation variations and they all failed.  Since the code is obviously fine typing-wise, I `# type: ignore`'d them.

Running mypy from the command line, cd'd into the leo-editor directory, resulted in mypy checking a lot more files and finding type errors in several (not qt_layout.py):

```
C:\Tom\git\leo-editor>py leo\scripts\mypy_leo.py leo\plugins\qt_layout.py
mypy_leo.py
leo\core\leoTokens.py:1141: error: Item "str" of "str | InputToken" has no attribute "kind"  [union-attr]
leo\core\leoTokens.py:1141: error: Item "str" of "str | InputToken" has no attribute "value"  [union-attr]
leo\plugins\qt_frame.py:537: error: Argument 1 to "keyRelease" of "EventWrapper" has incompatible type "LeoKeyEvent"; expected "QEvent"  [arg-type]
leo\plugins\nested_splitter.py:1009: error: Item "int" of "list[int] | int" has no attribute "append"  [union-attr]
leo\plugins\nested_splitter.py:1011: error: Item "int" of "list[int] | int" has no attribute "append"  [union-attr]
leo\plugins\nested_splitter.py:1011: error: Argument 3 to "getattr" has incompatible type "str"; expected "int"  [arg-type]
Found 6 errors in 3 files (checked 256 source files)
```

Good luck in fixing them!

**Review by edreamleo — APPROVED** [review]
@tbpassin Many thanks for all your work.

I'm sure you are frustrated by the testing issues. I'm not concerned about the mypy issues--I'll fix them after I merge the PR.

**Comment by edreamleo** [comment]
@tbpassin All tests pass after the merge. However, pylint complains about four long lines. No big deal.

I'll create a new PR that fixes the pylint complaints and attempts to remove the mypy suppressions.

**Comment by tbpassin** [comment]
Once again your pylint run and mine gave different results.  I ran Pylint from the minibuffer. I had no messages.

**Comment by edreamleo** [comment]
@tbpassin Please read carefully info item #2867. These are the tests I run. I expect you to do the same.

**Comment by tbpassin** [comment]
OK; did you realize that it's not on the list of info issues for developers?  I mean https://github.com/leo-editor/leo-editor/issues/910

**Comment by edreamleo** [comment]
@tbpassin Oops. Now #910 does mention #2867. But it has always been a `devinfo` item.

**Pull request merged**
