### PR TITLE
Fixed arguments handling and help-string(s) output

### PR DESCRIPTION
**Pull request by boltex**
Fixed arguments that were gathered, but not (re)assigned properly - I tried all arguments to make sure they work.
Also revised documentation and description strings.

### CODE REVIEW

**Comment by boltex** [comment]
@edreamleo DONT MERGE YET  problems with this new arguments getter that does not support arguments with double dash sent from a process spawn in nodejs! (but works if copy pasted on command line as-is!)

I reviewed the code 5 times now - everything matches and i cannot find why this happens!! (might revert to the old arguments system getter and remove the specific sub parameters of the 'trace' argument.)

**Comment by boltex** [comment]
argparse.ArgumentParser totally breaks leo integration :/

**Comment by boltex** [comment]
unrecognized arguments: --limit 2 --port 32125

But if vscode uses the single-dash ones it works :  -l 2 -p 32125

the double dashed arguments that still work with argparse.ArgumentParser are the boolean ones

**Comment by boltex** [comment]
Ok I found a solution in leoInteg : I have to pass the arguments parameters as separate 'arguments'. Meaning that Instead of this (where w_args is an array for argument strings):
   **w_args.push("--limit " + this._leoIntegration.config.limitUsers);**
to set an argument as **--limit 2**, with this new cli arg parsing librairy I have to do:
    **w_args.push("--limit");
    w_args.push(this._leoIntegration.config.limitUsers.toString());**

to then, finally, spawn the server process with the usual:
**this._serverProcess = child.spawn(w_pythonPath, w_args, w_options);**
Is this expected/normal?

**Comment by boltex** [comment]
I looked online at many examples and indeed, the argument parameters are usually passed as separate entries in the arguments array when calling 'spawn process' in nodejs.

So this pull request is good - except it will break the --limit x parameter with the current 0.1.7 beta of leointeg. So I'll release a 0.1.18 beta tomorrow (probably the last beta version until release)

**Review by edreamleo — APPROVED** [review]
Thanks for all these careful changes. They look good to me.

**Comment by edreamleo** [comment]
On Sun, Aug 22, 2021 at 7:39 PM Felix ***@***.***> wrote:

> So this pull request is good - except it will break the --limit x
> parameter with the current 0.1.7 beta of leointeg. So I'll release a 0.1.18
> beta tomorrow (probably the last beta version until release)
>

Just merged the PR. As usual, I've left the felix-server4 branch.

Many thanks for all this work!

Edward

**Pull request merged**
