### PR TITLE
PR fixes #3679: load to @auto if possible

### LINKED ISSUE #3679: Opening file on command line use @edit instead of @auto
The new ability to import files from the command line opens them as `@edit` nodes.  But _Import Any File_, and also drag-and-drop of a file onto the tree pane, opens them (usually, at any rate) as `@auto` trees.

I thought that the idea was that the new capability was to import them the same way as _Import Any File_.  That's certainly what I would like.  

Leo 6.7.6-devel, devel branch, build 1ca1bbfaa4
2023-11-28 04:53:24 -0600
Python 3.12.0, PyQt version 6.5.2
Windows 10 AMD64 (build 10.0.19045) SP0

### PR DESCRIPTION
**Pull request by edreamleo**
See #3679.

### CODE REVIEW

**Comment by edreamleo** [comment]
@tbpassin This PR is ready for review. It passes a simple test.

**Comment by edreamleo** [comment]
@tbpassin Rev d699dc4 does as you ask.

**Comment by tbpassin** [comment]
Don't forget to change `scanner_for_at_auto()` the same way.

**Comment by edreamleo** [comment]
@tbpassin Done at 9618433

**Review by tbpassin — APPROVED** [review]

**Pull request merged**
