### PR TITLE
Support for jinja viewrendering

### PR DESCRIPTION
**Pull request by sprajagopal**
The existing `jinja` plugin (EKR: jinjarender.py) has support to output to a file but doesn't show a live preview.
I modified `viewrendered.py` to include support for `@jinja` nodes. 

Usage:
1. Create a `@jinja` node
3. Create another child node to `@jinja` called `@jinja template`
    - The body of this node contains the path to the jinja template
2. Create a child node to `@jinja` called `@jinja inputs`
    - This node should contain child nodes with `@jinja variable <var>`
    - All occurrences of `{{ var }}` in template is replaced with the content of `@jinja variable <var>`
4. When `viewrendered` plugin is active, the output of the jinja rendering is shown in the preview pane. The output is also written to the body of the root `@jinja` node.

### CODE REVIEW

**Comment by edreamleo** [comment]
Thanks for this work. Let me know when it is ready to be merged.

**Comment by sprajagopal** [comment]
My branch seems to be behind leading to conflicts. I'll fix this and request review.

**Comment by edreamleo** [comment]
Imo, your code is Leonine. In particular, the "untangle" function expands section references and `@others` in the various nodes.

**Comment by sprajagopal** [comment]
> Imo, your code is Leonine. In particular, the "untangle" function expands section references and `@others` in the various nodes.

Could you please elaborate more? Should I rewrite without the "untangle" function because of these side effects?

**Comment by edreamleo** [comment]
@sprajagopal My comment about untangle was supposed to be a compliment :-)

Jinja2 is appropriate for my sabbatical. I have just today come up to speed with it.

I have lots of comments re @jinja. I'll discuss them next on leo-editor.

**Comment by edreamleo** [comment]
I fixed some minor conflicts involving imports by hand. I also fixed some pylint complaints. The new code is in devel. Many thanks for your work.

**Pull request merged**
