### PR TITLE
Jkn 4141 declutter

### PR DESCRIPTION
**Pull request by jknGH**
oops, probably should have written this earlier

This is to fix issue #4141, as discussed here: https://groups.google.com/g/leo-editor/c/K9FkwGXQltA

Two points:
* the default for the getattr has been changed - the font weight scaling is different in PyQt6
* I am unsure if the original `getattr(QtGui.Qfont, param...)` ever worked properly.

Tested by myself (under Linux) and @tbpassin 

worth squashing commits BTW ;-/

### CODE REVIEW

**Comment by tbpassin** [comment]
Just as a matter of interest, note that an integer (e.g., 500) can still be used instead of the enum expression (e.g., QtGui.QFont.Weight.Medium). Using the enum for the default is better because it directly communicates the intent.

**Comment by jknGH** [comment]
> Just as a matter of interest, note that an integer (e.g., 500) can still be used instead of the enum expression (e.g., QtGui.QFont.Weight.Medium). Using the enum for the default is better because it directly communicates the intent.

Agreed, but I hardly see the point. In C, I am hardly going to write

`#define PI (3.14)`

and then do

`circumference = 2 * r * 3.14;`

BTW, I have confirmed that the getattr() never used to work properly. On a system with PyQt5, I changed my declutter pattern to

`WEIGHT Normal`

and the headline was still shown as bold (ie the '75' in effect).

Of course there is no guarantee that a given font has all of the options available. I didn't think it worth adding a note about this, eg. in LeoDocs.leo. You can probably expect Normal and Bold to be present, I guess.

**Comment by tbpassin** [comment]
> Of course there is no guarantee that a given font has all of the options available

That's right. I think that Qt tries to come up with a font that's reasonably close if there isn't an exact match.  Some fonts can have non-existant weights created programmatically, I think, and some can't.

**Review by edreamleo — APPROVED** [review]
Thanks for this work.

**Comment by edreamleo** [comment]
@jknGH Is everything ready for merging?

**Comment by jknGH** [comment]
> @jknGH Is everything ready for merging?

@edreamleo I believe so, yes

**Comment by jknGH** [comment]
@edreamleo, I was leaving the 'merge pull request action to you. Is that not the way you want it done?

**Comment by edreamleo** [comment]
@jknGH Thanks for the clarification. I'll merge this PR now.

I usually like to do the merge myself. I then immediately run all of Leo's tests. If there are problems I fix them, create a PR and then merge the PR back into devel.

This workflow guarantees that everything works for me. The extra work is trivial. On a typical day I run all of Leo's tests dozens of time.

**Comment by edreamleo** [comment]
@jknGH All my tests pass after the merge :-)

**Comment by jknGH** [comment]
> @jknGH All my tests pass after the merge :-)

must be some new tests needed ;-)

(I think previously, a declutter line like eg.

```
WEIGHT light
```

would have given an actual bold font, if present. But I can understand there being no test for this

**Comment by edreamleo** [comment]
@jknGH My main concern when running tests is that Leo's core remains stable.

The authors of PRs are responsible for new unit tests, but I'm a prime offender, so don't worry ;-)

Indeed, Leo's unit tests run in a null gui. Leo has no good framework for testing gui code.

**Pull request merged**
