### PR TITLE
Use new layouts at startup

### PR DESCRIPTION
**Pull request by tbpassin**
This PR changes the Dynamic Window to create the initial layout using the qt-layout methods instead of the 6.8.1 code.  The user can change layouts without reloading the output and now all layouts can be defined in only one place, qt_layout.

- [x] Add new code to DW, remove obsolete layout code.
- [x] Combine "legacy" and "quadrant" layouts because they are actually the same.
- [x] Modify getVr() so it can be called correctly during DW startup.
- [x] `LayoutCacheWidget` in qt_layout makes sure VR3 is loaded during startup so that it can be placed into the right place in the initial layout. This causes an additional screen flash but only once, during Leo startup.
- [x] Minor cleanup of some layout nodes.
- [x] Added a command alias for 'layout-restore-default': 'layout-restore-to-setting'.
- [x] pylint: no errors.
- [x] pytest: `932 passed, 2 skipped, 2 warnings in 26.54s`
- [ ] mypy - mypy generates hundreds of errors for qt_frames unrelated to this PR.  It is impractical and undesirable to fix them all as part of this PR (see https://github.com/leo-editor/leo-editor/issues/4110).

### CODE REVIEW

**Comment by tbpassin** [comment]
Please see comment to https://github.com/leo-editor/leo-editor/pull/4103 because it may be hard to merge these two PRs.  They are not incompatible but I don't see how some of the changes can be blended together without some careful hand work.  At least, I don't know how to do that in a merge tool.  This PR should have priority and then we can see how to blend in changes from 4103.

**Review by edreamleo — APPROVED** [review]
I don't see anything that would generate "hundreds" of mypy complaints.

I'll handle any complaints that do appear after the merge.

**Comment by edreamleo** [comment]
@tbpassin All tests pass after the merge. Leo's beautifier changed `qt_frame.py`, but that's no big deal.

Many thanks for this PR.  Onward!

**Comment by tbpassin** [comment]
> I don't see anything that would generate "hundreds" of mypy complaints.

Maybe my copy of the mypy config file is different from yours for some reason.

**Pull request merged**
