### PR TITLE
PR for #3724: another colorizer bug

### PR DESCRIPTION
**Pull request by edreamleo**
See #3724.

### CODE REVIEW

**Review by tbpassin — COMMENTED** [review]
I see what you are doing with the `alt_delimiter`s and it looks all right as far as I can tell.  But I am not familiar with all the ins and outs of f-string quoting so I cannot say if all cases have been covered.  If you want me to I can study up on f-string quoting.

Shouldn't the AST module be able to work this out more  definitively?

**Comment by edreamleo** [comment]
On Thu, Dec 21, 2023 at 10:09 PM Thomas Passin ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> But I am not familiar with all the ins and outs of f-string quoting
>
See PEP 701 <https://peps.python.org/pep-0701/>, especially considerations
regarding quote reuse
<https://peps.python.org/pep-0701/#considerations-regarding-quote-reuse>.

Imo, this PEP was a mistake, for reasons discussed in the PEP itself.
However, there is nothing Leo can do *now* about this mistake.

I considered not changing the colorizer at all, but that point of view
seems a bit petulant :-)

Anyway, you don't have to comment further, Thomas, if you don't want to!

Edward

**Comment by tbpassin** [comment]
I did read that PEP when this issue came up, and I think it's completely wrong-headed.  String interpolation doesn't require you to insert a specific quoted string inside curly braces, it only requires Python to evaluate the contents of the curly brace before completing the construction of the f-string. And why worry that much about "compatibility" with those other languages when Python's use of whitespace is wildly incompatible?

But as you said we seem to be stuck with it for now.

**Comment by edreamleo** [comment]
@tbpassin "Reposting" as a separate comment to allow markup.

I could not have said it better myself.

The PR provides *no use case whatsoever* for the additional complications.

Earlier versions of Python provide straightforward ways of building complex f-strings from previous strings and f-strings.

Here is an example from leoAst.py:
```python
def compute_node_string(self, node: Node, level: int) -> str:
    """Return a string summarizing the node."""
    indent = ' ' * 2 * level
    parent = getattr(node, 'parent', None)
    node_id = getattr(node, 'node_index', '??')
    parent_id = getattr(parent, 'node_index', '??')
    parent_s = f"{parent_id:>3}.{parent.__class__.__name__} " if parent else ''
    class_name = node.__class__.__name__
    descriptor_s = f"{node_id}.{class_name}: {self.show_fields(class_name, node, 20)}"
    tokens_s = self.show_tokens(node, 70, 100)
    lines = self.show_line_range(node)
    full_s1 = f"{parent_s:<16} {lines:<10} {indent}{descriptor_s} "
    node_s = f"{full_s1:<62} {tokens_s}\n"
    return node_s
```

**Review by boltex — APPROVED** [review]

**Pull request merged**
