### PR TITLE
PR 2 for #4160: fix a path in pylint.get_rc_file

### PR DESCRIPTION
**Pull request by edreamleo**
See #4160.

### CODE REVIEW

**Comment by edreamleo** [comment]
@tbpassin This PR is ready for review. It passes my full suite of tests.

**Review by tbpassin — APPROVED** [review]

**Comment by tbpassin** [comment]
This change fixes the issue, of course.  However, the leo/test directory does not contain an rc file with the name being searched for.  Instead, it contains an rc file with this name: pylint-leo-rc-ref.txt. I wonder if this discrepancy is intentional or not. The way things are, a search that got as far as the leo/test directory would only succeed if the user had made a copy of pylint-leo-rc-ref.txt with the name that is being searched for.

**Comment by edreamleo** [comment]
@tbpassin The name `pylint-leo-rc-ref.txt` is intentional. Users should create their own rc file.

**Comment by tbpassin** [comment]
OK, that's what I suspected.

**Pull request merged**
