### PR TITLE
Backlink undirected

### PR DESCRIPTION
**Pull request by ATikhonov2**
It is a little fix of the Backlink plugin which does not let creating 'undirected' links between nodes and displays an AttributeError message in the Log pane on deleting a node with links

Repro steps:

1. Create a new Leo-outline
2. Enable the Backlink plugin (backlink.py) in the body of the node "@settings -> @enabled-plugins"
3. Create two top-level nodes "foo" and "boo"
4. Select node "foo"
5. In the "Link" pane click button "Place"
6. Select node "boo"
7. In the Link tab select the link direction "mark, undirected" and click button "Link"
8. See that no link has appeared
9. In the Link tab select the link direction "mark" and click button "Link"
10. Note that the link is created
11. Delete node "boo"
12. See a message "AttributeError: 'NoneType' object has no attribute 'h'" in the log pane

A link is not created at step#8 because only link direction strings "to" and "from" are handled in backling.py (method backlinkController.linkAction). The error appears because there is omitted check that a linked position exists in the outline.

Could you please review the suggested fix?

### CODE REVIEW

**Review by edreamleo — APPROVED** [review]
The changes look reasonable, but I am not really qualified to comment.

I'll approve these changes, trusting that the changes work for you.

**Comment by ATikhonov2** [comment]
Thanks! Indeed those modifications worked well in my local repository for about a month. Actually it is my first PR on GitHub ever. Should I do something else with it?

**Comment by edreamleo** [comment]
@ATikhonov2 Just hit the "Merge pull request" button :-)

**Comment by ATikhonov2** [comment]
I think that you see this page differently than I do - there is a message: 

> Only those with write access to this repository can merge pull requests.

I don't see the button "Merge pull request".

**Comment by edreamleo** [comment]
@ATikhonov2 I have merged your PR. Thanks for this work.

**Pull request merged**
