### PR TITLE
Felix server4

### PR DESCRIPTION
**Pull request by boltex**
I started by pulling the ekr-server-protocol which had your changes on leoserver and leoclient.

**I Fixed leoserver to work alongside leointeg's dev branch** which now also supports this new protocol for the minibuffer commands.

**But I have not touched at the modifications in leoclient.** (I'll let you assign me a new issue if the client/tests need fixing as so the unit tests run fine for the next release 6.4, ...if needed)

**EKR**: I reverted leoclient.py. The changes in that file were obsolete. I'll work on this later.

### CODE REVIEW

**Comment by boltex** [comment]
oh! I should have mentioned that this Fixes #2093 

:+1:

**Review by edreamleo — APPROVED** [review]
It looks like I moved some helper methods around, which makes the diffs harder to read, but I think everything is good. You made minor comment changes re kebab-case.

**Comment by edreamleo** [comment]
On Fri, Jul 23, 2021 at 12:03 AM Felix ***@***.***> wrote:

> oh! I should have mentioned that this Fixes #2093
> <https://github.com/leo-editor/leo-editor/issues/2093>
>
Yes. All user commands now appear in the minibuffer.

However, the @button commands don't work from the minibuffer in vs-code.
For example, in vs-code I opened leoPy.leo (my local copy of LeoPyRef.leo).
This file has an @button backup command. It works properly from the Leo
Buttons pane, but does *not* work from the "minibuffer", although
@button-back does appear in the minibuffer.

Edward

**Comment by edreamleo** [comment]
On Fri, Jul 23, 2021 at 5:21 AM Edward K. Ream ***@***.***> wrote:

> However, the @button commands don't work from the minibuffer in vs-code.
For example, in vs-code I opened leoPy.leo (my local copy of LeoPyRef.leo).
This file has an @button backup command. It works properly from the Leo
Buttons pane, but does *not* work from the "minibuffer", although
@button-back does appear in the minibuffer.

I put a trace in server._do_message.  When using the "Leo Buttons" pane,
the action is "!click_button".  But *nothing* happens when I choose the
button from leoInteg's "minibuffer".

Edward

**Comment by edreamleo** [comment]
On Fri, Jul 23, 2021 at 5:33 AM Edward K. Ream ***@***.***> wrote:

I put a trace in server._do_message.  When using the "Leo Buttons" pane,
> the action is "!click_button".  But *nothing* happens when I choose the
> button from leoInteg's "minibuffer".
>

Just created #180 <https://github.com/boltex/leointeg/issues/180>. I may be
to blame.  Or not :-)

Edward

**Comment by edreamleo** [comment]
On Fri, Jul 23, 2021 at 5:38 AM Edward K. Ream ***@***.***> wrote:

> Just created #180 <https://github.com/boltex/leointeg/issues/180>. I may
be to blame.  Or not :-)

PR #2097 <https://github.com/leo-editor/leo-editor/pull/2097> will cover
any needed python work.

Edward

>

-- 
-----------------------------------------------------------------
Edward K. Ream: ***@***.***
An old man, crazy about computer programming.
Leo Editor: http://leoeditor.com/
-----------------------------------------------------------------

**Pull request merged**
