### PR TITLE
PR: Fix bug in leoUndo.py

### LINKED ISSUE #3519: mark-first-parents and unmark-first-parents should be undoable like other 'mark' related commands.
See PR #3524.

mark-first-parents and it's unmark-first-parents sibling command should allow undo and redo to be performed. 

EKR: The legacy names are poor. I'll rename the commands to `mark-node-and-parents` and `unmark-node-and-parents`.

### PR DESCRIPTION
**Pull request by boltex**
This PR was originally a duplicate of PR #3524 (Fix #3519).

### CODE REVIEW

**Comment by boltex** [comment]
I also fixed a line order in leoUndo.py. 😎 All tests pass.

**Comment by boltex** [comment]
Oh oh - perhaps you didnt see I had fixed it last night? (this also contains a leoUndo.py fix)

**Comment by edreamleo** [comment]
@boltex No, I didn't see this PR. PR #3524 changes the names of the commands, and does not include your undo fix.

**Review by edreamleo — APPROVED** [review]
I have edited this PR to eliminate the diffs to `leo/commands/editCommands.py`.

As a result, this PR changes only `undo.py`, so I have also changed this PR's name.

**Pull request merged**
