### PR TITLE
PR for #3170: scrolling in the picture_viewer plugin

### PR DESCRIPTION
**Pull request by edreamleo**
See #3170.  I finally realized that I need `Slides.do_scroll`.  But it's not working.

### CODE REVIEW

**Comment by tbpassin** [comment]
You need to use _-dy_, then it works.

```
    try:
        self.scroll_lockout = True
        hbar.setValue(dx)
        vbar.setValue(-dy)  # <=======
    finally:
        self.scroll_lockout = False
```

But what do you have against having scrollbars?

**Comment by tbpassin** [comment]
I would never have expected this:

`ScrollBarPolicy.ScrollBarAlwaysOff` but you scroll by telling the scrollbar to do it anyway.

**Comment by edreamleo** [comment]
@tbpassin I tried this kind of code several time. Imo it has no chance of working, regardless of the sign of dy :-)

**Scrollbars**

I dislike scrollbars because:
1. They waste real estate (I usually use full-screen mode) and
2. It's better for me to avoid using the mouse. The arrow keys scroll properly.

As for scrollbar policy, it affects only the visibility of the scrollbars, not their functionality. Two asserts in the `do_scroll` method never fail:
```python
hbar, vbar = area.horizontalScrollBar(), area.verticalScrollBar()
...
assert hbar.isEnabled()
assert vbar.isEnabled()
```
**Traces**

The latest code in this PR significantly improves traces. For example, I opened a test folder, zoomed the first slide (slide 0), moved to the next slide and returned to slide 0 and then quit. The resulting traces shows that that the `x/y (dx/dy)` values are correct when returning to slide 0:
```console
Found 10 pictures in C:/Users/Edward Ream/Edward4/test

load_data: show_slide           0 scale:       1.0 x: 860 y: -332
save_data: zoom_in              0 scale:      1.05 x: 860 y: -332

load_data: show_slide           0 scale:      1.05 x: 860 y: -332
save_data: zoom_in              0 scale:    1.1025 x: 860 y: -332

load_data: show_slide           0 scale:    1.1025 x: 860 y: -332
save_data: next_slide           0 scale:    1.1025 x: 860 y: -332

load_data: show_slide           1 scale:  1.157625 x: 1020 y: -366
save_data: prev_slide           1 scale:  1.157625 x: 1020 y: -366

load_data: show_slide           0 scale:    1.1025 x: 860 y: -332
Writing C:\Users\Dev\.leo\picture_viewer.json
picture_viewer: done
```
*Note*: The traces in `load/save_data` show their calling methods,  `show_slide`, `zoom_in` or `zoom_out`, etc.

**Summary**

`show_slide` is calling `do_scroll` with the proper values of `self.dx` and `self.dy`! This is a new development :-)

Imo, the culprit in *drawing* the next slide is likely that "pre-existing" values for `self.scale`, `self.dx`, and `self.dy` are somehow interfering with the *creation* of the next slide.

My next idea: attempt to re-init the scroll area *before* creating the pixmap for the next slide.

**Comment by edreamleo** [comment]
@tbpassin Despite my comments about the scrollbars being enabled, I'm not convinced that calling `QScrollbar.setValue` is the right approach for this application. But first I'll try helping `setValue` by restoring the scroll area to a pristine state before creating the pixmap.

**Comment by edreamleo** [comment]
@tbpassin Looking at the trace above, I wonder whether the problem might involve altering scaling the `dx/dy` values.

Indeed, `show_slide` contains several lines like
```python
image1 = pixmap.scaledToHeight(int(self.height() * self.scale), transform)
```
At present, neither `show_slide` nor the `zoom_in/out` methods scale the `dx/dy` values. And maybe a good thing too, because the `dx/dy` values are *ints* not *floats*. It's a can of worms.

**Comment by edreamleo** [comment]
@tbpassin I'm stuck. After 36b25d0 I'm out of ideas. It's time for a break. This is a minor issue :-)

**Comment by tbpassin** [comment]
Maybe I have not tried enough variations on opening pictures, so I'll give you more details on what I did.  I created a folder with three jpeg images in it.  I opened it and observed that the program would display all three, although two were rotated.  Then I zoomed in on one of them so that it would be too large for the window, and then I panned it with arrow keys.

I closed the program and re-opened it.  I observed that this one picture was still zoomed in but not panned to the position it had when saved.  I did not zoom the other two pictures and so did not have any panning to check, though they did seem to be displayed the same size as before.

After I changed self.dy to -self.dy in the calls to the scrollbar, after restarting the program, the first image appeared zoomed to the same amount, but now it was panned to the position it had had before.

You may have noticed that I called the scrollbars after the pixmap was scaled and displayed, not before.

I wrote that "it works" because the zoom and pan states of the one image seemed to have been restored after restarting.

As an aside, I would have changed the code that decides whether to use image1 or image2, i.e., at

`image1 = pixmap.scaledToHeight(int(self.height() * self.scale), transform)`

I would have chosen based on the unscaled height and width.  Why do the transform on both when only the chosen one needs it?  Unscaled x and y values will both be scaled linearly, so will still have the same ordering before and after transform.

**Comment by edreamleo** [comment]
@tbpassin Great comments:
- You have probably solved the main problem: restoring the panned values.  I'll use your code.
- I have been fixated on what is likely a harder problem: restoring panned values when revisiting a slide during the same slideshow. Happily, this problem is much less important!
- I'll also take your advice and scale only the winning image.

**Comment by tbpassin** [comment]
With the code I posted, the zoom and pan do not change when I change slides and then return to them within the same session.  So I'm not seeing the problem that you see.

Remember, I'm using the code from a few days ago, before your recent changes, and before the advent of `do_xxx()`.  I just changed the code where the stored values are applied.

What's important but not addressed in this thread is preventing an image from being rotated 90 deg when it should not be.  The two of mine that are wrongly rotated are both portrait orientations.   IOW, they have the height larger than the width.  The landscape image isn't rotated being, and that is correct.

**Pull request merged**
