### PR TITLE
Fix VR3 handling of missing @jupyter modules

### PR DESCRIPTION
**Pull request by tbpassin**
1. Fix missing error for nbconvert;
2. Improve error messages for missing imports for @jupyter nodes.
3. Version to 3.8.
test-all:

```
Ran 920 tests in 18.484s
OK (skipped=8)
```

### CODE REVIEW

**Review by edreamleo — CHANGES_REQUESTED** [review]
Doing AI on the exception is not necessary.  Please split the import into two pieces, with a clear explanation in each "except" block about how to install the missing package.

**Comment by tbpassin** [comment]
All right, changes have been pushed.

**Review by edreamleo — APPROVED** [review]

**Comment by edreamleo** [comment]
@tbpassin Good work. I got the message about `pip install nbconvert`, and doing so eliminated all messages from VR3.

**Comment by tbpassin** [comment]
Good to hear!  I tested it by mis-spelling the names of the modules (like xnbconvert) in the source code rather than by actually uninstalling anything.

**Pull request merged**
