### PR TITLE
leoCommands: execute-external-file command: runs files with ".bash" 

### PR DESCRIPTION
**Pull request by tbpassin**
extension (in Linux);  Bug fix for processing `@data` node.

### CODE REVIEW

**Review by edreamleo — APPROVED** [review]
I'll approve this PR. It looks like you copied/pasted most (all?) of the nodes in this file, thereby changing their gnxs (node sentinels).

**Comment by edreamleo** [comment]
Rev 064401b in devel fixes a pylint complaint about `elif` after `continue`.

**Comment by tbpassin** [comment]
> It looks like you copied/pasted most (all?) of the nodes in this file, thereby changing their gnxs (node sentinels).

That's true.  It seemed easier to copy a working node  from the Linux VM where I worked it out than to make sure I transcribed it correctly.  I should have pasted it as a clone, as I can see now.

**Comment by edreamleo** [comment]
On Thu, Mar 9, 2023 at 8:06 AM Thomas Passin ***@***.***>
wrote:

> It looks like you copied/pasted most (all?) of the nodes in this file,
> thereby changing their gnxs (node sentinels).
>
> That's true. It seemed easier to copy a working node from the Linux VM
> where I worked it out than to make sure I transcribed it correctly. I
> should have pasted it as a clone, as I can see now.
>
No problem. Nobody is ever going to care :-)

Edward

**Pull request merged**
