### PR TITLE
PR 2 for #3915

### PR DESCRIPTION
**Pull request by edreamleo**
See #3915.

This PR replaces PR #3928. It contains only harmless changes.

### CODE REVIEW

**Review by tbpassin — COMMENTED** [review]
[leoapp.py]
-   Line 3376 (not part of the PR)
    `self.edit_headline = 'Recent files. Do not change this headline!'`

   This could be a class level attribute or a module level symbolic constant.  It's not really an instance variable.

Everything else seems all right to me.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comment. The `edit_headline` ivar and its logic is mysterious to me. It's part of a dubious feature that I never use.

**Comment by tbpassin** [comment]
I looked for uses and found three of them.  It seems to be used as a target for a search so it shouldn't have the text changed (unless it becomes a symbolic name at a higher level).  Why one might want to search for it I haven't looked into.

**Comment by edreamleo** [comment]
@tbpassin I don't understand and I don't want to investigate :-)

**Comment by tbpassin** [comment]
With the latest devel branch I don't see those three usages anyway.

**Comment by edreamleo** [comment]
@tbpassin :-)

**Pull request merged**
