### PR TITLE
Assembly 6502 colorizer

### PR DESCRIPTION
**Pull request by gatesphere**
Added a colorizer mode for 6502 assembly.

### CODE REVIEW

**Comment by gatesphere** [comment]
I sloppily made my todo.py icon fix directly in my devel branch.  I apologize for the messy PR this created.

**Comment by edreamleo** [comment]
@gatesphere Thanks for the work. However, the changes to todo.py are a deal breaker. I had to make big changes to todo.py for #1846. Resolving the conflicts would not be fun.

Please close this PR and create another one without todo.py.  Thanks.

**Comment by gatesphere** [comment]
Will do, thanks.

**Comment by gatesphere** [comment]
Submitted #1885 as a new, clean PR.

**Pull request closed without merging**
