### PR TITLE
PR for #2957: Rewrite sort-children

### PR DESCRIPTION
**Pull request by edreamleo**
See #2957.

- [x] Split the two sort commands into entirely separate pieces, eliminating the evil 'sortChildren' kwarg.
- [x] Rewrite sort-children.
- [x] Rewrite sort-siblings.
- [x] Retire beforeSort* methods.
- [x] Revise undo/redo/Sort* methods.
- [x] Retire setPositionAfterSort.
- [x] Move dump methods into LeoUnitTest class.
- [x] Create leo/unittests/commands/test_outlineCommands.py.
- [x] Remove strange unit-test-related assertion in undo code.
- [x] Create unit tests for sort-children and sort-siblings.

### CODE REVIEW

**Comment by tbpassin** [comment]
sort-children and sort-siblings both leave the after-sort focus on the initial before-sort node.  I'm happy with that.

**Comment by tbpassin** [comment]
There is a `u.afterSortSiblings`, but I don't see a matching `u.beforeSortSiblings`.  Same for sorting children.

Is that intentional, or an oversight?

**Comment by edreamleo** [comment]
@tbpassin Yes, retiring u.beforeSort* was intentional, as indicated in the PR's checklist.

If I were writing the Undoer class now I would do the following:

- Eliminate most u.before* methods.
  The u.after* methods can contain the "before" and "after" snapshots.
- Eliminate most Undoer ivars.
   Instead, the undo/redo methods could get their data from the g.Bunches the after methods create.

**Comment by tbpassin** [comment]
Thanks.  Also, I noticed in `u.afterChangeBody` an admonition not to use a ternary operator:

```
    # Careful: don't use ternary operator.
    if w:
        bunch.newSel = w.getSelectionRange()
    else:
        bunch.newSel = 0, 0  # pragma: no cover
```

Just for my education, why is that?  I thought that the first part of the ternary expression would not be executed if the condition were False, so why would there be a problem with the following ternary?

```
bunch.newSel = w.getSelectionRange() if w else 0, 0
```

**Comment by boltex** [comment]
@tbpassin maybe because the last comma at the end of the line, **to mean the set 0,0**  makes it indeterminate if the bunch._newSel (which is a set of 2 numbers) is first the ternary, then the ",0"  as the last number of the set. or both at once as the 'else' of the ternary " 0 , 0" 

(sorry if this is unclear, i didnt have cofee today yet)

**Comment by edreamleo** [comment]
@tbpassin Félix is correct: it is a bit tricky to use the ternary operator with tuples. But this should work:

    bunch.newSel = w.getSelectionRange() if w else (0, 0)

Perhaps the comment is a holdover from an ancient confusion of mine, which I finally got clear about. For *one-element tuples only*, a trailing comma is required to denote the tuple, like this `(0,)` or this `tuple(0)`.

**Pull request merged**
