### PR TITLE
Revise setup.py, w/o importing leo and with new tests

### PR DESCRIPTION
**Pull request by edreamleo**
**Important**: The crucial define_entry_points function is unchanged, except for formatting.

**Summary of changes**

- Always use a **static** version number, defined in setup.py itself.
  Use neither the git version nor leo.core.leoVersion.version.
- Check the version with a regex matching only a limited number of valid version numbers:
  `pattern = re.compile(r'[0-9]+\.[0-9]+(\.[0-9]+)?((b|rc)[0-9]+)?')`
   That is: `N1.N2(.N3)?(bN|rcN)?`
- Besides the standard library, import only setuptools.
  - Don't use semvar library.
  - Import neither leoGlobals.py nor leoVersion.py.
- Add print_exception function and get_readme_contents functions.
- Add is_valid_version, test_is_valid_version, and dump_entry_point functions.
- Set `universal=0` in setup.cfg.  setup.py itself must be run with python 3.
- Use open, not codecs.open. The encoding of README.md is known!

Acknowledgement: I could not have begun this work without Matt's previous work.

### CODE REVIEW

**Comment by maphew** [comment]
Hi Edward! A fortuitous review request. I've been on holiday and this is first time I've looked at github notification in weeks. 

I've always been a little disquieted by the extensive scaffolding required for reading a version number from within the Leo depths, so I'm happy to see that removed in favour of some hard coded simplicity. 

_Starting my review now..._

**Comment by maphew** [comment]
The `build` module is new to me, thanks for the heads up. It should be added to `pyproject.toml` so it's picked up as a build requirement and auto-installed by Travis et al. And also to setup.py `install_requires`, so it's ready at hand for Leo devs\*.

There are 3 batch files in `./leo/dist` - _build-check, build-exe, build-wheel_ that are orphaned from LeoDist.leo. Build-wheel could be updated to use `python -m build` (or maybe just removed).

---
\* Conventionally install_requires is supposed to be the _minimal_ package set needed to run the application and one is supposed to use different constructs for developers. However after spending many many days trying and failing to acheive the same install simplicity for developers without overloading install_requires I give up. I now personally redefine _minimal_ in the Leo context to be _recommended_, as in: all batteries included.

**Review by maphew — APPROVED** [review]

**Comment by maphew** [comment]
I neglected to also say: the revised setup.py work fine on my machine (Python 3.6.10 :: Anaconda, Inc.) , according to _build-check_ and `python -m build` which prior to today had not seen a git pull from the Leo repository since the middle of winter.

**Comment by edreamleo** [comment]
@maphew Many thanks for you helpful comments and code additions!

The [revised packaging guide](https://packaging.python.org/tutorials/packaging-projects/) seems much more comprehensible than before. After reading the guide and setup.py I think (at long last!) that I understand the basics. But I'm still a newbie. For example, I would not have thought to add build.py to the install_requires list.

**Comment by maphew** [comment]
Thank you in turn for asking my opinion. :)  ...there's been a number of changes to the packaging guide since I last paid real attention. I knew setup.py is slowly moving towards deprecation in favour of pyproject.toml but was unaware of setup.cfg's upgraded status.

**Comment by edreamleo** [comment]
@maphew You're welcome.

I am going to try pushing the b2 distro to testpypi, but I don't think there is a need to create a pypi distro for Leo 6.4b2.

Matt, are you still willing to do the pypi release for Leo 6.4 (final)?

**Pull request merged**
