### PR TITLE
PR for #4139: leo/modes/jupytext.py

### PR DESCRIPTION
**Pull request by edreamleo**
See #4139.

This PR delegates all coloring to Python and Markdown modes.
This new colorizing pattern uses only two rules!
It took a *huge* amount of work to make the result as straightforward as it is.

- [x] Create `leo/modes/jupytext.py`.

I allowed no *changes* to methods in `leoColorizer.py` except:

- [x] `init_mode`: Add a helpful warning if importing a file in `leo/modes` fails.

This PR *adds* two methods to `leoColorizer.py`:

- [x] Add `match_span_delegated_lines` and its helper.

**Other changes**

- [x] Update the Jupytext importer so it generates `@language jupytext`.
- [x] Update the corresponding unit test.

Last-minute testing shows that this PR *must* be merged into devel.

- [x] Update language-description dicts in `leoApp.py`.

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex @HaveF @tbpassin This PR is ready for review.

I gave myself until yesterday to finish, but maybe I can bend the rules a bit an include this in Leo 6.8.2. What do you think?

**Review by tbpassin — APPROVED** [review]
I don't have any specific lines to comment on.

I tried out the new colorizer mode by changing the `@language python` to `@language jupytext` in a `@jupytext` file.  It seems to do what is expected, although I am not sure if colorizing text within quotes should be done.

I'm not very enthusiastic about all this new code going into an official release such a short time after it's been written.  But I suppose if some problems crops up it will only affect the few users who have expressed an interest in @jupyter.  I think that's only three people so far ...

**Comment by edreamleo** [comment]
@tbpassin Last-minute testing shows that the language-description dicts *must* be updated.

I'm not worried about `@language jupytext`. Leo's (unchanged!) coloring infrastructure is rock solid.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your approval. I shall do the merge now so more people can test devel.

**Comment by tbpassin** [comment]
Before going to release, remember to have the `@jupytext importer` insert `@language jupytext` instead of `@language python`.

**Comment by edreamleo** [comment]
@tbpassin Already done: Jupytext import adds `@language jupytext`.

**Pull request merged**
