### PR TITLE
PR: Quirp in editFileCommands not properly fixed

### PR DESCRIPTION
**Pull request by edreamleo**
- [x] Create m.group(1) the `section_pat` regex.

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex Please take a look :-)

**Review by boltex — COMMENTED** [review]
The one just before the make_clones  method was this:
section_pat = re.compile(r'\s*<\<(.*)>\>')

The original had (.*) instead of (.+) which is **match zero or more of the preceding character** instead of **one or more of the preceding character** so perhaps that was also an important thing in the proper regex which was used.

**Comment by edreamleo** [comment]
@boltex Yes, there is a change.  Imo `.+' is better than `.*`.

**Comment by boltex** [comment]
Oh ok great then, i'll approve it

**Review by boltex — APPROVED** [review]
As per your last email,  (.+) is even better :)

**Pull request merged**
