### PR TITLE
PR for #3759: '\r' in pasted text

### PR DESCRIPTION
**Pull request by edreamleo**
See #3759.

- [x] Massage cut/copied/pasted text as follows:
   ` s = s.replace('\r\n', '\n').replace('\r', '\n')`
   This pattern occurs in many places in Leo.
- [x] Simplify the cut logic!

A: Do the following common logic once, after possibly recalculating i and j:

```python
 s = w.get(i, j)
 w.delete(i, j)
 w.see(i)  # Required.
 s = s.replace('\r\n', '\n').replace('\r', '\n')  # 3759.
 g.app.gui.replaceClipboardWith(s)
```

B: Delete the following do-nothing lines:

```python
elif name.startswith('head'):
    # The headline is not officially changed yet.
    s = w.getAllText()
```
This last assignment to s has no side effects, so it should be removed!

**Discussion**

The change to the cut logic is potentially risky. I have taken that risk because:
- Leo's unit tests cover cut/copy/paste thoroughly.
- The new code eliminates confusing and redundant calls to `w.get` and `w.getAllText`.

These changes might affect either LeoJS or LeoInteg.

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex Please review this PR. I'll wait for your approval before merging it.

**Comment by edreamleo** [comment]
@boltex Please carefully review the changes to the cut logic. They are potentially risky!

**Review by boltex — APPROVED** [review]
I looked at those changes. This makes sense to me.
Again, I'll implement them into leojs and see if anything broke.

**Comment by edreamleo** [comment]
@boltex Thanks for your review.

**Pull request merged**
