### PR TITLE
PR for #3977: save-file-as-zipped

### PR DESCRIPTION
**Pull request by edreamleo**
See #3977.

- [x] The both forms of the command name.
- [x] Change the method name.
- [x] Change the docstring.

These first two changes are minor breaking changes. I'll document these changes in the 6.8.0 branch.

### CODE REVIEW

**Review by boltex — APPROVED** [review]
Aaahhh.... !  This feels so much better! Hehe! 😆

**Comment by edreamleo** [comment]
@boltex Thanks for your approval.
@tbpassin Thanks for raising this issue!

**Review by tbpassin — COMMENTED** [review]
! Approved.  Thanks.

**Review by boltex — COMMENTED** [review]
Oops - I missed this line which was just following the lines you've modified !

**title="Save As Zipped",**

**Comment by edreamleo** [comment]
@boltex Fixed at rev d8ffe6a.

**Pull request merged**
