### PR TITLE
PR for #4012: dialog does not return proper values.

### PR DESCRIPTION
**Pull request by edreamleo**
See #4012.

At last I found a strategy that does not depend on enums:

- [x] Set button names to each button's desired return value.
- [x] Use `dialog.clickedButton` to get the clicked button.
- [x] Return `dialog.clickedButton.objectName() or 'cancel'`.
- [x] Fix `qt_gui.runAskYesNoDialog`.
- [x] Simplify `qt_gui.runAskYesNoCancelDialog`.
- [x] Improve a misleading comment in `qt_gui.runSaveFileDialog`.

### CODE REVIEW

**Comment by edreamleo** [comment]
@tbpassin Whew. Finding a straightforward strategy took a lot of experimenting.

**Comment by tbpassin** [comment]
Didn't you look at my PR? It uses button_clicked and returns the documented return values, unlike this PR.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your approval.

As for the ints, the Qt API is a right mess. There are at least two enums involved, but they don't cover all the cases! Imo, `dialog.buttonClicked` is the only way around the mess.

I won't merge this PR until I check all the other Qt dialogs.

**Comment by tbpassin** [comment]
I checked the other one like this - `runAskYesNoCancelDialog` - and it uses dialog.clickedButton(). The return value is computed in an awkward and less clear way compared with this PR.  The dialog as is does return the right values, but would be simpler and cleaner reworked with the approach used in this PR.

**Comment by edreamleo** [comment]
@tbpassin I'll simplify `runAskYesNoCancelDialog` as part of this PR.

**Comment by edreamleo** [comment]
@tbpassin The changes to `qt_gui.runAskYesNoCancelDialog` are ready for your review.

**Review by tbpassin — CHANGES_REQUESTED** [review]
_runAskYesNoCancelDialog()_
In Line 598 we do a `buttonClicked()` inside the `try` block but don't pick up th3 value.  Later in line 604 we do it __again__: ` button = dialog.clickedButton()`.  If the `try` block failed, then the second invocation will probably fail too.

I suggest adding `button = None`  before the `try` block.  Then do the ` button = dialog.clickedButton()` inside the `try` block instead of at line 604. Then line 604 becomes

`        return  button.objectName if button else 'yes'`

[Or maybe we don't need the `try` block at all]

**Comment by edreamleo** [comment]
@tbpassin Rev 91f6ebaf makes the changes you suggest.

The `try/finally` block insures that the code in the `finally` *always* gets executed.

**Comment by edreamleo** [comment]
@tbpassin Ready for another approval :-)

**Review by tbpassin — APPROVED** [review]

**Comment by edreamleo** [comment]
@tbpassin Thanks for your second approval.

**Pull request merged**
