### PR TITLE
PR: rpcalc plugin

### PR DESCRIPTION
**Pull request by edreamleo**
The rpcalc plugin by @tbpassin.  After enabling the plugin clicking the `RPCalc` shows a calculator in the log pane. I see three problems:

**Problem 1**: The following checks fail:  <details>
```console
FAIL: test_all_qt_plugins_call_g_assertUi_qt_ (leo.unittests.test_plugins.TestPlugins)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Repos\leo-editor\leo\unittests\test_plugins.py", line 96, in test_all_qt_plugins_call_g_assertUi_qt_
    self.assertTrue(re.search(r"g\.assertUi\(['\"]qt['\"]\)", s), msg=fn)
AssertionError: None is not true : C:/Repos/leo-editor/leo/plugins/rpcalc.py


mypy-leo
leo\plugins\rpcalc.py:200: error: Variable "leo.plugins.rpcalc.QWidget" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:200: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
leo\plugins\rpcalc.py:200: error: Invalid base class "QWidget"  [misc]
leo\plugins\rpcalc.py:341: error: Variable "leo.plugins.rpcalc.QLabel" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:341: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
leo\plugins\rpcalc.py:341: error: Invalid base class "QLabel"  [misc]
leo\plugins\rpcalc.py:377: error: Variable "leo.plugins.rpcalc.QPushButton" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:377: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
leo\plugins\rpcalc.py:377: error: Invalid base class "QPushButton"  [misc]
leo\plugins\rpcalc.py:899: error: Variable "leo.plugins.rpcalc.QWidget" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:899: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
leo\plugins\rpcalc.py:899: error: Invalid base class "QWidget"  [misc]
leo\plugins\rpcalc.py:1012: error: Need type annotation for "mainDict" (hint: "mainDict: Dict[<type>, <type>] = ...")  [var-annotated]
leo\plugins\rpcalc.py:1454: error: Variable "leo.plugins.rpcalc.QLCDNumber" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:1454: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliasesleo\plugins\rpcalc.py:1454: error: Invalid base class "QLCDNumber"  [misc]
leo\plugins\rpcalc.py:1488: error: Variable "leo.plugins.rpcalc.QFrame" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:1488: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliasesleo\plugins\rpcalc.py:1488: error: Invalid base class "QFrame"  [misc]
leo\plugins\rpcalc.py:1564: error: Variable "leo.plugins.rpcalc.QTreeWidget" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:1564: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliasesleo\plugins\rpcalc.py:1564: error: Invalid base class "QTreeWidget"  [misc]
leo\plugins\rpcalc.py:1698: error: Variable "leo.plugins.rpcalc.QWidget" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:1698: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliasesleo\plugins\rpcalc.py:1698: error: Invalid base class "QWidget"  [misc]
leo\plugins\rpcalc.py:1825: error: Variable "leo.plugins.rpcalc.QMainWindow" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:1825: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliasesleo\plugins\rpcalc.py:1825: error: Invalid base class "QMainWindow"  [misc]
leo\plugins\rpcalc.py:1928: error: Variable "leo.plugins.rpcalc.QTextBrowser" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:1928: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliasesleo\plugins\rpcalc.py:1928: error: Invalid base class "QTextBrowser"  [misc]
leo\plugins\rpcalc.py:2051: error: Need type annotation for "dfltDict" (hint: "dfltDict: Dict[<type>, <type>] = ...")  [var-annotated]
leo\plugins\rpcalc.py:2052: error: Need type annotation for "userDict" (hint: "userDict: Dict[<type>, <type>] = ...")  [var-annotated]
leo\plugins\rpcalc.py:2204: error: Variable "leo.plugins.rpcalc.QDialog" is not valid as a type  [valid-type]
leo\plugins\rpcalc.py:2204: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliasesleo\plugins\rpcalc.py:2204: error: Invalid base class "QDialog"  [misc]
Found 25 errors in 1 file (checked 262 source files)
```

</details>

**Problem 2**: Clicking the `OPT` button gives this traceback: <details>

```console
Uncaught exception in Leo...
Traceback (most recent call last):
  File "C:\Repos\leo-editor\leo\plugins\rpcalc.py", line 1310, in issueCmd
    self.setOptions()
  File "C:\Repos\leo-editor\leo\plugins\rpcalc.py", line 1089, in setOptions
    self.optDlg = OptionDlg(self.calc.option, self)
  File "C:\Repos\leo-editor\leo\plugins\rpcalc.py", line 2211, in __init__
    self.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint |
AttributeError: type object 'Qt' has no attribute 'Dialog'
```
My environment:
```console
Leo 6.7.3-devel, ekr-rpcalc-plugin branch, build a086326398
2023-04-30 05:48:23 -0500
Python 3.10.5, PyQt version 6.4.3
Windows 10 AMD64 (build 10.0.22621) SP0
```

</details>

**Problem 3**: I don't see an `=` button!  How do I do `2 * 3 = 6`?

### CODE REVIEW

**Comment by tbpassin** [comment]
This is why I didn't create a PR.  The plugin is useful as is, but not ready to go into Leo's repo.

1. Type checks haven't been set up yet so no wonder it fails a lot of them;
2. I didn't notice the Opt button error because I don't use it much;  it used to work, so I probably accidentally deleted the QDialog import as I refactored the imports.  In the original code, all those classes were in separate python files, each with its own imports.
3. This is an RPN calculator, of course it does not have an equals sign!  As I wrote in my post, to add two numbers, enter the first and press &lt;ENTER> to push it on the stack.  Enter the second one and click or type "+".  This is exactly like using FORTH, and much like using LISP S-expressions, where you might write `(2 3 +)` to get 5.  You can click the ENT button instead of typing &lt;ENTER>.  It's also how GF4 works.

I've been developing the plugin in my own branch in my clone of the Leo repo.  Now that you have created this unmerged PR, I don't know how I should proceed, GitHub-wise.  I could fix something in my branch and create a PR for it.  But leoPyRef has to be changed to add the new plugin file and directory, and by the time that happens the devel branch will have changed.

OTOH, when I make changes in my branch, they will make your PR out of date.  So how should I handle this situation?

**Comment by edreamleo** [comment]
@tbpassin I'll close this PR. Please file a new PR whenever you like.

**Comment by tbpassin** [comment]
Most of those mypy messages are for this kind of construction:

`QLabel = QtWidgets.QLabel`

mypy thinks that the left side is a variable but a method definition should have a type  for its arg(s).  It seems that this can be fixed by the following:

`QLabel: type[QtWidgets.QLabel] = QtWidgets.QLabel`

See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases

This is horrible to read and I don't see that doing so helps the code quality at all.  I'd rather tell mypy to skip these checks, if that's possible.

What do you think I should do about this?

**Comment by edreamleo** [comment]
@tbpassin There are several solutions:

- Use `Any` as the type.
- Add a comment of the form `# type:ignore` at the end of specific lines.
- To suppress all mypy checks add  `# type:ignore`  at the very start of the file.

**Comment by tbpassin** [comment]
> * To suppress all mypy checks add  `# type:ignore`  at the very start of the file.

This does nothing.  Supposedly mypy has a PR that adds this functionality but maybe I don't have a recent enough version.  See

["# type: ignore" to ignore more than one line](https://mail.python.org/archives/list/typing-sig%40python.org/thread/35BCWKS6QOITCDYJ55LRBJ55XE76NI6E/)

**Comment by edreamleo** [comment]
@tbpassin `# type:ignore` appears at the start of `leoflexx.py`, `leoQt5.py` and `leoQt6.py`.

These appear to work as expected:

`python -m mypy --version` reports `mypy 0.982 (compiled: yes)` with `Python 3.10.5`.

**Comment by tbpassin** [comment]
I have 
```
C:\Users\tom>py -m mypy --version
mypy 1.2.0 (compiled: yes)
```

**Pull request closed without merging**
