### PR TITLE
Viewrendered3 Updates For 6.8.0 Free Layout Changes

### PR DESCRIPTION
**Pull request by tbpassin**
I merged today's 6.8.0 into my branch and then resolved all conflicts for viewrendered3.py by accepting its new code everywhere.

Version to 5.0.

(If this PR isn't simple enough, I'll start a whole new branch, but in this case I made no changes to any 6.8.0 code except for VR3).

### CODE REVIEW

**Comment by edreamleo** [comment]
@tbpassin My apologies for the delay in responding to this PR.

Please issue a new PR (based on devel) that changes only VR3. I'll merge the new PR before releasing 6.8.0.

**Comment by tbpassin** [comment]
I'm somewhat confused by what has gone on with this file, but I've just compared the version in devel with the version as I remember leaving it - before all the free-layout changes - and I think devel has all the changes I wanted back them.

Based on changes in various gnx's I speculate that you copied the VR3 file from my branch at some point and made a lot of changes to it, then merged *that* into devel.

Anyway, I will delete the branch this PR was based on, and if I think any more changes are needed I will start a new branch for them.

**Comment by tbpassin** [comment]
The current version of VR3 in devel contains nodes like this: _TomP.20191215195433.82_.  That's not my user name.  My user name is "tom", and my nodes have GNXs like this: _tom.20240602185043.1_.

What the ****?

**Comment by edreamleo** [comment]
@tbpassin Mysterious. I'm pretty sure I didn't do anything with your gnxs!

It looks like somebody copied and pasted the whole file. That would explain the `.82` at the end.  You could do the same to change `TomP.` to `tom.`.

**Comment by tbpassin** [comment]
> It looks like somebody copied and pasted the whole file.

Someone who knows I often use "TomP" in posts.  Strange.

Some things I thought I had handled (like absolute paths to image files) aren't handled in devel's version.  I'll have a PR for them soon, based on this morning's devel pull.

**Pull request closed without merging**
