### PR TITLE
Replace g.os_path_expandExpression by c.expand_path_expression

### PR DESCRIPTION
**Pull request by edreamleo**
In the VR, VR2 and VR3 plugins.

### CODE REVIEW

**Comment by tbpassin** [comment]
What do you need from me, Edward?

**Comment by edreamleo** [comment]
@tbpassin A favorable review :-)

**Comment by tbpassin** [comment]
The VR3 file in leo:no-docks is identical to my own copy.  It passes all the usual tests I use for RsT, MD, and Asciidoc.  Pylint rated it at 10.00/10.  So it passes my review.  If you need me to take some action in GitHub, please let me know what it is.

**Comment by tbpassin** [comment]
Grrr, I hadn't realized there is now a expand-expr branch.  I will check what's on there.

**Comment by tbpassin** [comment]
OK, I have now update my repo to the  expand-expr branch, made sure that the version I have checked has the change, and VR3 still passes all my checks including pylint (no surprise).  I also checked VR and VR2, and I see that you made the change there, too.

So my review gives this branch a pass.

**Comment by edreamleo** [comment]
Thanks, Thomas.  I'll merge now.

**Pull request merged**
