### PR TITLE
PR for #3816: improved UNLs

### PR DESCRIPTION
**Pull request by edreamleo**
See #3816. This PR was easier to do than I imagined. It makes minor, easily understood, changes in the expected places, namely `g.findAnyUnl`,  `g.openUNLFile` and the regex in `g.getUNLFilePart`.

- [x] Add easy special case to `g.findAnyUnl`.
- [x] Make the gnx part optional in the `file_part_pattern` used by `g.getUNLFilePart`.
- [x] Add easy special case to `g.openUNLFile` for file parts containing `os.sep`.
   In addition, improve the `standard` function.
- [x] Add new test cases to `test.leo`. Everything appears to work as expected.
   All unit tests pass.
- [x] Update the documentation in the section `<< About clickable links >>`.

The new code uses `@data unl-path-prefixes` only for *short* (not relative) paths.
Imo, this behavior is both reasonable and compatible with all existing UNLs.

### CODE REVIEW

**Review by tbpassin — CHANGES_REQUESTED** [review]
This PR does open the file containing a relative UNL in the same directory if it includes a node part (gnx or path-based) but it does not open the outline if there is no node part.

Without a node specifier, this new code (line 6803ff in leoGlobals.py) is not called:
```
        if not tail:
            c2 = g.openUNLFile(c, file_part)
            return c2.p if c2 else None
```
This is probably because the tail part is not empty as expected (and it's also missing its first character.  I.e., "flexx_test.leo" becomes "lexx_test.leo".

**Comment by tbpassin** [comment]
Aha, I hadn't realized a plain file name needs to have a '#' character appended.  I looked at the regexes and then I realized it.  So now both these forms work for me:

`unl:gnx://flexx_test.leo#`
`unl://flexx_test.leo#`

For both, the target outline opens if it isn't open already.
Also, an outline one level up opened with

`unl://../<filename>`

Based on this testing, I think this PR is ready.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comments. I'll merge this PR after updating some comments.

**Review by boltex — APPROVED** [review]
I've also tested with `../myFile.leo` to see if the relative path work with `../` to go 'UP' a folder. Even `../anotherSideFolder/otherLeoFile.leo` worked to go up a folder, and back down into ANOTHER folder. Impressive. 

UNLs Works as expected -> resolving relative chunks of paths just like a regular web URL! 

Thanks for this feature! This rocks! 😄

**Comment by boltex** [comment]
@edreamleo @tbpassin To celebrate this achievement for the UNLs to honor any relative path given, I thought you'd like to see that once converted line-by-line into javascript, it even works (relative paths that go up with `../../' and back down into other directories) in vscode on the web with LeoJS ! (in the next beta version coming out in less than a week)

Screenshot as proof below:
image

**Comment by tbpassin** [comment]
Great going, @boltex! 

I think of these cross-outline navigable links as letting us easily create webs of documents and navigate around them, without web servers or needing to run them through a system like Sphinx.

I mentioned in an earlier comment (maybe on another comment thread) wanting to link to places in documents like _LeoDocs.py_. I have been learning that many times it's easier for me to find something in the outline, using the Nav pane, than in the rendered Sphinx set of HTML pages.  If I want a rendered view of a section, I can always view it in VR3. Now I will be able to link to those places easily.

**Pull request merged**
