### PR TITLE
Made es and es_print output to terminal if server loop is not ready. Fixes #3953

### LINKED ISSUE #3953: python leo/core/leoserver.py --port 32125 InternalServerError
Leo 6.7.1, master branch, build f2520500c0
2022-11-08 10:28:41 -0600
Python 3.12.0, PyQt version 6.5.3
darwin

> python leo/core/leoserver.py --port 32125 

runs well.

***

But Leo 6.7.9-devel, devel branch, build 376b554c0d call errors below:

Leo Log Window
Leo 6.7.9-devel, devel branch, build 376b554c0d
2024-05-28 13:22:39 -0500
Python 3.12.0, PyQt version 6.5.3
darwin
setting leoID from os.getenv('USER'): 'swot'
      home: /Users/swot
leo-editor: /Users/swot/app/leo-editor
      load: /Users/swot/app/leo-editor/leo/core
    config: /Users/swot/app/leo-editor/leo/config
reading settings in /Users/swot/app/leo-editor/leo/config/leoSettings.leo
reading settings in /Users/swot/.leo/myLeoSettings.leo

> python leo/core/leoserver.py --port 32125

Starting LeoBridge Server 1.0.11 (Launch with -h for help)
duplicate, (not conflicting) key bindings in myLeoSettings.leo
all    BackSpace do-nothing
text   BackSpace backward-delete-char
duplicate, (not conflicting) key bindings in myLeoSettings.leo
all    Delete do-nothing
text   Delete delete-char
redefining abbreviation date;;
from '{|{x=time.asctime()}|}' to '{|{x=time.strftime("%Y/%m/%d")}|}'
redefining abbreviation lc;;
from '@language cplusplus\n' to '@clean '
redefining abbreviation html;;
from '<html>\n<head>\n<title><|title|></title>\n<style>\n</style>\n</head>\n<body>\n<|content|>\n</body>\n</html>' to '@language xml\n<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width" />\n    <title><||></title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script src="./js/vue.js"></script>\n    <script src="./main.js"></script>\n  </body>\n</html>'
redefining abbreviation ,,
from "{|{x='__NEXT_PLACEHOLDER'}|}" to '__NEXT_PLACEHOLDER'
Traceback (most recent call last):
  File "/Users/swot/app/leo-editor/leo/core/leoserver.py", line 5752, in <module>
    main()
  File "/Users/swot/app/leo-editor/leo/core/leoserver.py", line 5700, in main
    controller = LeoServer()  # Single instance of LeoServer, i.e., an instance of leoBridge
                 ^^^^^^^^^^^
  File "/Users/swot/app/leo-editor/leo/core/leoserver.py", line 901, in __init__
    self.dummy_c = g.app.newCommander(fileName=None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 1520, in newCommander
    c = leoCommands.Commands(fileName,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swot/app/leo-editor/leo/core/leoCommands.py", line 166, in __init__
    c.finishCreate()  # Slightly slow.
    ^^^^^^^^^^^^^^^^
  File "/Users/swot/app/leo-editor/leo/core/leoCommands.py", line 447, in finishCreate
    c.abbrevCommands.finishCreate()
  File "/Users/swot/app/leo-editor/leo/commands/abbrevCommands.py", line 60, in finishCreate
    self.reload_settings()
  File "/Users/swot/app/leo-editor/leo/commands/abbrevCommands.py", line 66, in reload_settings
    self.init_abbrev()
  File "/Users/swot/app/leo-editor/leo/commands/abbrevCommands.py", line 101, in init_abbrev
    self.addAbbrevHelper(s, tag)
  File "/Users/swot/app/leo-editor/leo/commands/abbrevCommands.py", line 742, in addAbbrevHelper
    g.es_print('redefining abbreviation', name,
  File "/Users/swot/app/leo-editor/leo/core/leoserver.py", line 1050, in _es
    self._send_async_output(package, True)
  File "/Users/swot/app/leo-editor/leo/core/leoserver.py", line 5259, in _send_async_output
    raise InternalServerError(f"\n{tag}: loop not ready {jsonPackage} \n")
InternalServerError:
send async output: loop not ready {"async":"log","log":"redefining abbreviation date;; \nfrom '{|{x=time.asctime()}|}' to '{|{x=time.strftime(\"%Y/%m/%d\")}|}'"}

### PR DESCRIPTION
**Pull request by boltex**
Fixes #3953

### CODE REVIEW

**Review by boltex — COMMENTED** [review]
Thanks to @wangzhaohe for spotting this ! 😊

**Review by edreamleo — APPROVED** [review]

**Comment by edreamleo** [comment]
The print statements should be disabled if `g.unitTesting` is True.

**Comment by edreamleo** [comment]
Fixed at rev b44616b in devel.

Are you running unit tests before requesting a review???

**Comment by boltex** [comment]
@edreamleo Sorry about this, I usually do - I'll make sure to run them even for small additions such as this

**Comment by edreamleo** [comment]
@boltex Thanks.

**Pull request merged**
