### PR TITLE
Enable Travis-CI on master branch

### PR DESCRIPTION
**Pull request by maphew**
Part of #672. Merging this .travis.yml will enable travis-ci testing. 

From that point forward every commit will trigger a travis build and test. Build status and history can be viewed at https://travis-ci.org/leo-editor/leo-editor

If the commit is a tag AND the branch the commit is in is _master_ travis will also attempt to deploy a release automatically to PyPi.org. (Pypi will reject tags that don't look like version numbers, I think; untested)

The `travis_tests` folder is optional at this point because there are no real tests in it. It can be removed, or moved elsewhere. It's there for illustration.

### CODE REVIEW

**Comment by maphew** [comment]
PR title says 'merge into master' but finishing the PR actually only pulls into `devel`. Going ahead with that. After this Travis will start automatically testing devel branch.

**Comment by technatica** [comment]
Have you looked at building an appimage?

It would make installing on Linux for non-technical users a snap. Oh,
wait... :-)

Chris

**Comment by technatica** [comment]
https://docs.appimage.org/packaging-guide/other-resources/travis.html

**Comment by maphew** [comment]
Thanks for the idea and pointer @technatica. I've used AppImage before (Krita, Onenote) but not looked at how they're made. After a cursory run through the docs it feels like it's at least as complicated as setup.py and pip. I've barely got my head around that so it'll be some time before I'll be ready to dig deeper. ;-) Feel free to open an enhancement issue for it though. Maybe someone else will jump in.

**Pull request merged**
