### PR TITLE
PR for #3141: restart command crashes

### PR DESCRIPTION
**Pull request by edreamleo**
See #3141.

- [x] Use `Popen.run` to do the restart.
- [x] Add print statements showing the arguments to `Popen.run`.

**Note**: The revised code calculates the files to be reloaded from the open outlines, not the original invocation of Leo.

### CODE REVIEW

**Comment by edreamleo** [comment]
@tbpassin This PR is ready for your testing.

**Review by tbpassin — CHANGES_REQUESTED** [review]
Line 126:
`python = 'py' if g.isWindows else 'python'`

This is plain wrong.  On Linux the executable name is usually "python3" - I don't know about the Mac - but on any platform the user might be using some other version of Python (e.g., python3.12 vs the system's default python3.11).

Always use `sys.executable` instead.

Line 129 - I know that the option _--no-splash_ can come after the file list, but I'd rather follow normal useage and put all the options first.

**Review by tbpassin — CHANGES_REQUESTED** [review]
This solution does not solve the problem. After restart begins, Leo emits the following and then hangs:
```
C:\Tom\git\leo-editor>Leo 6.7.9-devel, ekr-3141-restart-crash branch, build 9edd07a887
2024-04-23 15:24:50 -0500
Python 3.12.3, PyQt version 6.6.2
Windows 10 AMD64 (build 10.0.19045) SP0
```
Pressing &lt;ENTER> allows the launch to continue.  
After manually closing a Leo session launched by `restart-leo`, the terminal window also hangs until &lt;ENTER> is pressed.

Also, Leo should remember and use the _--theme=_ option that was used for the original startup. (Perhaps all the command-line options be remembered and used?)

Tested on Windows with 9edd07a8874912e85931e21310fa83360a8f936f.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your comments. I'll investigate further and do more thorough testing.

**Comment by tbpassin** [comment]
I'll test your branch first.  I will also test it on Linux.  About the differences, I don't know what could be different between our two systems.  I always get my terminals using `<WIN_KEY>-R cmd /k aliases`.  _aliases_ is a batch file that loads some _doskey_ shortcuts.  Maybe that's involved somehow.  I will check that out by using a pristine cmd session.

Oh, I wonder if the terminal is the difference.  There is a newish "terminal" program which can be run instead of the older cmd window we all used to use.  If you are running it (possibly without realizing it's different) that could be a difference.

**Comment by tbpassin** [comment]
The current version of this branch on Linux (XUbuntu) failed to start with this message:
```
    from leo.commands import commanderFileCommands
  File "/home/tom/git/leo-editor/leo/commands/commanderFileCommands.py", line 131
    command = fr"  {executable_s}{'\n'}  {'\n  '.join(args)}"
                                                             ^
SyntaxError: f-string expression part cannot include a backslash
```
I've got Python 3.11 on this VM, vs 3.12 on Windows.  Didn't 3.12 change the syntax for f-strings a bit?

**Comment by edreamleo** [comment]
@tbpassin Good catch, Thomas. I'll test a fix with 3.9.

**Comment by tbpassin** [comment]
I don't think any major Linux distro uses Python higher than 3.11 yet - at least, none of my usual VM distros do.

**Comment by tbpassin** [comment]
In Linux, using the current version of devel, things are even worse - a `restart-leo` command leaves you at a working command line `<ENTER>` doesn't cause Leo's restart to continue.  I haven't found a way to have it continue as yet.

**Comment by edreamleo** [comment]
@tbpassin I'm using `command.exe` with the (Vanilla, I think) `Command Prompt` configuration.

**Comment by tbpassin** [comment]
ChatGPT suggests starting the new Leo session using POpen and then closing the existing instance.  I haven't tried it.  Of course, ChatGPT doesn''t know all the complications involved in closing Leo.
```
    def restart_program(self):
        # Get the Python executable path and the script path
        python_executable = sys.executable
        script_path = os.path.abspath(__file__)

        # Launch a new instance of the program using subprocess
        subprocess.Popen([python_executable, script_path])

        # Close the current instance of the program
        sys.exit()
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for the hint from ChatGPT.  I'll play with it.

**Comment by edreamleo** [comment]
@tbpassin The latest rev uses Popen. On my machine I need to hit `<return>` only after exiting the *restarted* process.

Overall, I think Popen is better. It feels snappier and there is no need to quote everything.

What do you think?

**Comment by tbpassin** [comment]
I tried it and still have the same problems.  I do agree the code is a little easier.

But **Success** (at least on Windows) - I replaced Popen with run and now it works without needing the `<ENTER>`s -

`subprocess.run(popen_args)`

**Comment by edreamleo** [comment]
@tbpassin Excellent. I'll commit your version next.

**Comment by tbpassin** [comment]
I take it back - on Linux using `subprocess.run(popen_args)` did not require a final ENTER after manually closing the re-started session. I had forgotten to manually change the code last time.

However, I noticed that the restarted session did not open an outline I had opened while the original session was running.  I saw this on Linux but I suppose it is probably the same on Windows.

**Comment by edreamleo** [comment]
@tbpassin You are correct. The `restart-leo` command only reopens the outlines that were opened when the `restart-leo` command is executed.

Please approve this PR. We can discuss enhancing it later, but that's a low priority for me.

**Review by tbpassin — APPROVED** [review]

**Comment by edreamleo** [comment]
@tbpassin Thanks for your approval. The first comment in this PR mentions that the code only opens outlines that are open at the time the user executes `restart-leo`.

**Pull request merged**
