### PR TITLE
PR for #3934: undo for clone-to-at-spot

### PR DESCRIPTION
**Pull request by edreamleo**
See #3934.

- [x] Undo the operation using `u.beforeUndoGroup` and u.`afterUndoGroup`.
- [x] As before, revert to initial state if the clone would be invalid.

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex I'm not sure this PR does what you want. However, I think *in this case only* a two-step undo is convenient.

**Comment by boltex** [comment]
@edreamleo Could an undo group not be favorable so as to be undone / redone in one step?

**Comment by edreamleo** [comment]
@boltex Yes, the command could be undone in one step. Would a two-step undo would be inconvenient?

**Comment by edreamleo** [comment]
@boltex Ready for review.  Undo/redo work (in one step) properly regardless of whether an `@spot` node exists.

The tricky part is undoing and redoing `c.p`.  All my hand tests now work as expected.

**Comment by boltex** [comment]
Thank you for making it a one-step undo. 

 I work in front-end, UI, and interface design and interaction. In that field, the concept of a "more than one step" undo is an unthinkable cardinal sin! Hahah! :)  (an undo action should be a one-shot action that reverts the last command, if undoable)

Many thanks again for re-considering and making the command!! 😄

**Review by boltex — APPROVED** [review]
This looks good!! Many thanks!

**Comment by edreamleo** [comment]
@boltex Thanks for your comments and approval.

**Pull request merged**
