### PR TITLE
PR for #3268: memory lead after deleting log

### PR DESCRIPTION
**Pull request by edreamleo**
See #3268.

### CODE REVIEW

**Comment by edreamleo** [comment]
@tbpassin This one-line fix is experimental. Please take a look.

**Comment by tbpassin** [comment]
It's probably a good idea, though I would have thought that the garbage collector would take care of it.  When a tab in the log frame is closed, I wonder if `deleteLater()` should be called on each of its Qt objects.  The whole `deleteLater()` thing is still mysterious to me.

But I really meant something else.  I meant the tab for an outline, rather than a tab in the log panel.  That is, the outline's tab above the menu bar.  There's probably a different name for it that I don't remember.

**Comment by edreamleo** [comment]
@tbpassin Thanks for the clarification.

The leak you speak of may occur in `qtFrame.destroySelf`. This method contains a comment that it can't call qtFrame.destroyAllObjects because event handlers can't be cancelled.

I would rather not mess with this problem. There may be a leak, but I don't think it's important. Remember that because of undo Leo can *never* delete VNodes for an outline. Leo must live with those "infinite" lifetimes.

**Comment by tbpassin** [comment]
I thought that undo was on a per-outline basis.  Wouldn't that allow vnodes to be deleted when the outline were closed? I don't expect undo to survive an outline close/reopen event.

**Comment by edreamleo** [comment]
@tbpassin What you say is true. I wasn't clear. I meant to say that Leo already "leaks" VNodes *until* the outline is closed.

Anyway, there is no way to fix this issue unless Leo can call `qtFrame.destroyAllObjects` when closing an outline. Doing so is harder than it looks because of queued event handlers.

**Comment by tbpassin** [comment]
Let's just close this one...

**Comment by edreamleo** [comment]
@tbpassin I agree with closing this issue. Thanks, though, for raising this issue.

**Pull request closed without merging**
