### PR TITLE
PR for #3970: nav shortcuts

### PR DESCRIPTION
**Pull request by edreamleo**
See #3970.

**Background and summary**

The `new-file` command generates an `after-create-leo-frame` event, so event handling is not likely an issue.

Within the plugin `Ctrl-g` works, but `Alt-x` does not. This PR does *not* add this binding because doing so requires changes to Leo's general key-handling code. It's too late to make such changes for Leo 6.8.0.

- [x] Make a hard binding of `find-quick-selected` to the `Shift-Control-f`.
- [x] Extra: Fix crasher in key-binding tracing code.

### CODE REVIEW

**Comment by tbpassin** [comment]
I only see changes to trace code.  Should I wait on reviewing for more code changes?

**Comment by edreamleo** [comment]
@tbpassin Please wait until the PR is no longer a draft.

**Comment by edreamleo** [comment]
@tbpassin This PR is ready for review. This PR is basically a hack, but a more general approach will have to wait until Leo 6.8.1.

**Review by tbpassin — APPROVED** [review]

**Comment by edreamleo** [comment]
@tbpassin Thanks Thomas.

**Pull request merged**
