### PR TITLE
PR for #2938: crash in isearch helper

### PR DESCRIPTION
**Pull request by edreamleo**
See #2938.

### CODE REVIEW

**Comment by tbpassin** [comment]
When I made the default to be  `w=c.miniBufferWidget`, I found that typing another character made it show up in the minibuffer, which seemed like a good choice since the user can see what was typed.  If the default  is `w = None`, I don't think the user will see any keystroke, will they?  Just because no match was found shouldn't prevent the user from seeing the typed character.

My test was to type a single "!", which was matched somewhere, then a second "!" which was not.  The second "!" appeared in the minibuffer.

**Comment by edreamleo** [comment]
@tbpassin Thanks for your testing. As you say, the PR's present code is not correct.

**Comment by edreamleo** [comment]
@tbpassin Assigning `w=None` works. The culprit, surprisingly, was k.updateLabel.

**Review by boltex — APPROVED** [review]
I tried it and it no longer crashes, also, the code looks pretty good to me!

 (although i am not very familiar with the widgets)
  :)

**Comment by edreamleo** [comment]
@boltex Thanks for your testing :-)

**Review by tbpassin — CHANGES_REQUESTED** [review]
This does not fix the original problem.  In `find.iSearch_helper`, a keystroke in the minibuffer that is not matched now does indeed display in the minibuffer, but the helper code still fails with no widget at `c, binding='BackSpace', char='\b', w=w`:

```
Traceback (most recent call last):
  File "c:\Tom\git\leo-editor\leo\plugins\qt_events.py", line 138, in eventFilter
    k.masterKeyHandler(key_event)
  File "c:\Tom\git\leo-editor\leo\core\leoKeys.py", line 3126, in masterKeyHandler
    if k.doMode(event):
  File "c:\Tom\git\leo-editor\leo\core\leoKeys.py", line 3306, in doMode
    handler(event)
  File "c:\Tom\git\leo-editor\leo\core\leoFind.py", line 2725, in isearch_state_handler
    self.iSearch_helper()
  File "c:\Tom\git\leo-editor\leo\core\leoFind.py", line 2697, in iSearch_helper
    c, binding='BackSpace', char='\b', w=w)
UnboundLocalError: local variable 'w' referenced before assignment
```

**Comment by edreamleo** [comment]
@tbpassin The code you show does not exist in devel rev cdecbd4.

**Comment by boltex** [comment]
@tbpassin you're probably testing devel or some other branch, because I confirm what @edreamleo just said.

**Comment by tbpassin** [comment]
Hmm, I had patched in the change to `k.updateLabel` as in the PR.  In the PR when I looked, I only saw listed that one change to the one file, so I didn't change anything else.  Now I see more changes in #2938.  Sorry for causing confusion.

Oh, yes, and changing to `w = None` did fix the crash problem, I just tried it.

**Pull request merged**
