### PR TITLE
For auto-md files, insert space after headline introducer ('###', etc)

### PR DESCRIPTION
**Pull request by tbpassin**
Some MD processors require a space here.  This PR parallels a similar change for VR3.

### CODE REVIEW

**Review by edreamleo — CHANGES_REQUESTED** [review]
Thanks Thomas. I'm a bit concerned about adding extra leading whitespace to headlines.  How about this?

`self.put(f"{'#' * level} {p.h.lstrip()}")  # Leo 6.6.4: preserve spacing.`

**Comment by tbpassin** [comment]
I see what you are thinking of - just in case p.h has leading whitespace. Who knows what one or another MD processor would do?  Yes,  I agree.

Why don't you go ahead and make the same change in VR3's code?  I just checked it and it too could end up with an extra space.  The code is at line 3484:  Change

```
headline_str = '## ' + headline
```
to
```
headline_str = '## ' + headline.lstrip()
```

**Comment by edreamleo** [comment]
@tbpassin Please add the call to lstrip to this PR. I'll then approve it. If you like you can make the change to the VR3 plugin in this same PR. Thanks.

**Comment by tbpassin** [comment]
Superceded by PR https://github.com/leo-editor/leo-editor/pull/2918, which adds a space and lstrips() the headline for VR3 and @auto-md files.

**Review by edreamleo — COMMENTED** [review]
devel already has these changes!

**Comment by edreamleo** [comment]
@tbpassin No problem.

**Pull request closed without merging**
